### ISSUE TITLE
'Wanted' not displaying all results on version v0.9

### ISSUE THREAD

**Issue by maxtheking** [morpheus65535/bazarr#1036]
**Describe the bug**
When clicking the 'Wanted' section on Version v0.9 it does not display all results. You can see in the sidebar is says '29' after 'Series', but only a single result is being displayed, while it does say 'Showing 1 to 25 of 29 entries'. See screenshot  below.

**To Reproduce**
1. Click on Wanted -> Your library.

**Expected behavior**
All results of wanted subtitles are being shown.

**Screenshots**
[Screenshot](https://i.maxkoning.nl/chrome_ZRaBQg2Gma.png)

**Software (please complete the following information):**
 - Bazarr: [v0.9]
 - OS: Docker on Debian 10 x64

**Comment by morpheus65535** [comment]
Can you send me your bazarr.db please? Can be in private on Discord.

**Comment by PotatoQuality** [comment]
Hmm, seeing the same issue on my side

**Comment by morpheus65535** [comment]
Yes I found the issue. It's related to the only monitored settings for Sonarr and Radarr. If have it enabled you will only see a partial list. I'm working on a fix.

**Comment by morpheus65535** [comment]
Should be fixed in v0.9.0.1 currently in dev branch. Can you confirm please?

**Comment by PotatoQuality** [comment]
Doesn't fix it on my end yet.
![image](https://user-images.githubusercontent.com/2944704/88695817-b381f600-d102-11ea-8203-1115f7fed4fd.png)

**Comment by morpheus65535** [comment]
> Doesn't fix it on my end yet.

Hotio's unstable image have ended rebuild at the same moment you wrote this post. Are you sure you got the updated image?

**Comment by PotatoQuality** [comment]
@morpheus65535 looking good, fixed the problem here on my end!
I assumed that the last update included already the code patch.
(Im on linuxserver/bazarr/ btw)

**Comment by morpheus65535** [comment]
LSIO's images aren't rebuild as often as Hotio's.

@maxtheking is it fixed for you also?

**Comment by PotatoQuality** [comment]
i will swich to hotio's then ;)

**Comment by morpheus65535** [comment]
I'll close this issue, please re-open if you still have problem.
