### ISSUE TITLE
BAZARR unable to sync subtitles using English audio track (a:0)

### ISSUE THREAD

**Issue by cphmichael** [morpheus65535/bazarr#1069]
I have a lot of those errors in the log:

* BAZARR unable to sync subtitles using English audio track(a:0): /movies/Rambo Last Blood (2019)/Rambo Last Blood (2019) Remux-2160p.en.srt
* BAZARR unable to sync subtitles using English embedded subtitle track(s:0): /movies/Terminator Dark Fate (2019)/Terminator Dark Fate (2019) Remux-2160p.en.srt
* BAZARR unable to sync subtitles using English embedded subtitle track(s:0): /movies/Maleficent Mistress of Evil (2019)/Maleficent Mistress of Evil (2019) Remux-2160p.en.srt
* BAZARR unable to sync subtitles using English embedded subtitle track(s:0): /movies/The Informer (2019)/The Informer (2019) Remux-1080p.en.srt
* Synchronization failed; consider passing --max-offset-seconds with a number larger than 600

Attached logfile:
[bazarr.log](https://github.com/morpheus65535/bazarr/files/5072894/bazarr.log)

**Comment by isaksamsten** [comment]
I have a similar issue with many films.

   BAZARR unable to sync subtitles using English embedded subtitle track(s:0): Film.mkv

When inspecting the file with `ffprobe` (`ffprobe -loglevel error -select_streams s -show_entries stream=index:stream_tags=language -of csv=p=0 Film.mkv`)

This is the output:

   2,eng
   3,eng
   4,chi
   5,chi

If I understand `ffprobe` correctly there is no subtitle track `s:0`? And even if track 0 is mapped to the first line (`2,eng`) this is the forced track meaning that it won't sync with an international translation.

**Comment by morpheus65535** [comment]
Fixed in next release.

**Comment by isaksamsten** [comment]
Still not resolved. But I guess this is a bug for ffsubsync now

**Comment by morpheus65535** [comment]
> Still not resolved. But I guess this is a bug for ffsubsync now

You're right, there's nothing more I can do on my side.

**Comment by isaksamsten** [comment]
Do you know how the subtitle track is chosen by ffsubsync. Perhaps bazarr could allow you to choose which subtitle track or audio track to use as reference

**Comment by morpheus65535** [comment]
I would ask smacke about it. TBH, I already regret to have implemented this functionality that is causing me more trouble than good. I keep answering the same questions again and again. Users expect this functionality to make miracle out of bad subtitles... that's unrealistic.

**Comment by isaksamsten** [comment]
I understand you! In my case the sub syncs fine if the correct subtitle track is chosen :-)

Bazarr is an excellent piece of software irrespective of subsyncing (which actually works super well for most tv subs where there is only one sub or audio track!)

Thanks for your efforts!
