### ISSUE TITLE
Provider Zimuku Scoring issue

### ISSUE THREAD

**Issue by yimingzhaomath** [morpheus65535/bazarr#1113]
**Describe the bug**
I am attaching a picture where the subtitle name is almost identical to that of the scene name, but the score is 70.

**To Reproduce**
The scene name is Blindspot.S05E11.1080p.WEB.H264-METCON[rarbg]
The provider is Zimuku

**Expected behavior**
The score should be much higher?? In particular, Bazarr says "year" does not match, which is weird because it's a show?

**Screenshots**
<img width="795" alt="Screen Shot 2020-09-16 at 11 24 49 AM" src="https://user-images.githubusercontent.com/13087183/93359207-548e5280-f810-11ea-94f6-4813928f65b5.png">

**Software (please complete the following information):**
 - Bazarr: 0.9.0.3
 - Radarr version 0.2.0.1504
 - Sonarr version 3.0.3.927
 - OS: linux

**Comment by morpheus65535** [comment]
Series also have year. I would need to see the not matching dropdown content for that subtitles.

**Comment by yimingzhaomath** [comment]
@morpheus65535 Here you are.

<img width="795" alt="Screen Shot 2020-09-16 at 11 37 36 AM" src="https://user-images.githubusercontent.com/13087183/93359919-1d6c7100-f811-11ea-88f2-c4b6f2853e32.png">

**Comment by morpheus65535** [comment]
Year could have already been fixed in dev branch. You can try it. As for release_group, `chs` is probably used instead of `METCON` so they don't match.

**Comment by yimingzhaomath** [comment]
I switched to the dev branch and manually triggered "Update Bazarr from source on Github" task. It updated my Bazarr to 0.9.0.4. But the "year" problem is still there.

**Comment by morpheus65535** [comment]
I've just pushed a fix to dev branch. Can you test it and confirm if the results are more accurate?

**Comment by yimingzhaomath** [comment]
Works like a charm! Many thanks!

**Comment by morpheus65535** [comment]
Good news! Enjoy!
