### ISSUE TITLE
[Provider] www.subs4series.com isn't working

### ISSUE THREAD

**Issue by zzecool** [morpheus65535/bazarr#1117]
Even thought https://www.subs4series.com/ is full of subtitles for "Raised by Wolves" im not getting any automatically or by manual search in bazarr. 

proof : https://www.subs4series.com/tv-series/raised-by-wolves/se08669ee03/season-1

bazarr doesn't throw any error in logs for this provider 
![image](https://user-images.githubusercontent.com/2816897/93712066-cd1c4880-fb5b-11ea-9f55-40f7b966c2f5.png)

**Software**
 - Bazarr: [v0.9.0.3]
 - Sonarr version [v 3.0.3.928]
 - OS: [Linuxserver Docker]

Thanks in advance.

**Comment by sotiris-bos** [comment]
I am getting the same on subs4free.

Some results show up but none that seem to match the movie. Movie is "Hit and Run 2012".

I get results for "Hit and Run Squad 2019", "The Man Who Killed Hitler and Then The Bigfoot 2018" etc but not my movie when searching through Bazarr.

Searching through subs4free gets me valid subtitles.

**Comment by halali** [comment]
Already fixed in dev branch. It because provider have wrong release name info.

**Comment by zzecool** [comment]
@halali 
> Already fixed in dev branch. It because provider have wrong release name info.

This doesn't to be "fixed" in dev branch.

Auto still fails to download any subtitle and Manual search finds the subtitle but doesn't download if you press the button.

![image](https://user-images.githubusercontent.com/2816897/93720149-e5a65600-fb8f-11ea-9a0c-d818da411f41.png)

This is the error in log for the manual button :

`Couldn't convert subtitle  to .srt format: Traceback (most recent call last):  File "/app/bazarr/bazarr/../libs/subliminal_patch/subtitle.py", line 287, in is_valid    subs = pysubs2.SSAFile.from_string(text)  File "/app/bazarr/bazarr/../libs/pysubs2/ssafile.py", line 126, in from_string    return cls.from_file(fp, format_, fps=fps, **kwargs)  File "/app/bazarr/bazarr/../libs/pysubs2/ssafile.py", line 153, in from_file    format_ = autodetect_format(fragment)  File "/app/bazarr/bazarr/../libs/pysubs2/formats.py", line 67, in autodetect_format    raise FormatAutodetectionError("No suitable formats")pysubs2.exceptions.FormatAutodetectionError: No suitable formats`

Kind regards.

**Comment by morpheus65535** [comment]
What if you manually download the subtitles file? Can you provide me a download link?

**Comment by zzecool** [comment]
Yes @morpheus65535  the link for the download isn't direct ( never was ) :

`https://www.subs4series.com/greek-subtitles/s42dce9537b/raised-by-wolves-s01e07-webrip-x264-ion10-720p1080p-hmax-web-dl-dd5-1-h-264-ntg-1080p-web-h264-videohole`

It has a recaptcha checkbox.

Thanks in advance.

**Comment by morpheus65535** [comment]
Could be a duplicate of #913. Never get properly fixed because it would require to implement anti-captcha for this provider and nobody have the time and the knowledge to do it. Only a part of this provider users seems to be required to solve captcha but I'm not sure why.

**Comment by morpheus65535** [comment]
Just tested it and it works for me... really strange...

![image](https://user-images.githubusercontent.com/5130500/93950171-cd117980-fd10-11ea-8112-0290ebb3dfc1.png)

**Comment by zzecool** [comment]
@morpheus65535  did you actually checked that it downloaded the sub ? Cause when i press the button it feels like it does the download but in log i get the following :

`BAZARR No valid Subtitles file found for this file: /tv/Raised by Wolves (2020)/Season 1/Raised by Wolves (2020) S01E07 Faces (1080p HMAX Webrip x265 10bit AC3 5.1 - Goki)[TAoE].mkv`

**Comment by morpheus65535** [comment]
@zzecool yes I can download the subtitles without any issue. Can you provide a debug log while reproducing the issue?

**Comment by zzecool** [comment]
@morpheus65535  of course, here you are clean fresh log of the procedure in pastebin + local :

https://pastebin.com/TqcrDiLQ

`23/09/2020 13:51:19|INFO    |root                            |BAZARR Log file emptied|
23/09/2020 13:51:30|DEBUG   |root                            |Bazarr version: 0.***.***.***|
23/09/2020 13:51:30|DEBUG   |root                            |Bazarr branch: master|
23/09/2020 13:51:30|DEBUG   |root                            |Operating system: Linux-4.4.59+-x86_64-with|
23/09/2020 13:51:30|DEBUG   |root                            |Python version: 3.8.5|
23/09/2020 13:51:30|INFO    |apscheduler.scheduler           |Added job "Update Series list from Sonarr" to job store "default"|
23/09/2020 13:51:30|INFO    |apscheduler.scheduler           |Added job "Sync episodes with Sonarr" to job store "default"|
23/09/2020 13:51:30|DEBUG   |apscheduler.scheduler           |Looking for jobs to run|
23/09/2020 13:51:30|INFO    |apscheduler.scheduler           |Added job "Update Movie list from Radarr" to job store "default"|
23/09/2020 13:51:30|DEBUG   |apscheduler.scheduler           |Next wakeup is due at 2020-09-23 13:52:30.624073+03:00 (in 59.996140 seconds)|
23/09/2020 13:51:30|INFO    |apscheduler.scheduler           |Added job "Update all Episode Subtitles from disk" to job store "default"|
23/09/2020 13:51:30|DEBUG   |apscheduler.scheduler           |Looking for jobs to run|
23/09/2020 13:51:30|INFO    |apscheduler.scheduler           |Added job "Update all Movie Subtitles from disk" to job store "default"|
23/09/2020 13:51:30|DEBUG   |apscheduler.scheduler           |Next wakeup is due at 2020-09-23 13:52:30.624073+03:00 (in 59.990792 seconds)|
23/09/2020 13:51:30|INFO    |apscheduler.scheduler           |Added job "Update Release Info" to job store "default"|
23/09/2020 13:51:30|DEBUG   |apscheduler.scheduler           |Looking for jobs to run|
23/09/2020 13:51:30|INFO    |apscheduler.scheduler           |Added job "Search for wanted Series Subtitles" to job store "default"|
23/09/2020 13:51:30|DEBUG   |apscheduler.scheduler           |Next wakeup is due at 2020-09-23 13:52:30.624073+03:00 (in 59.986621 seconds)|
23/09/2020 13:51:30|INFO    |apscheduler.scheduler           |Added job "Search for wanted Movies Subtitles" to job store "default"|
23/09/2020 13:51:30|DEBUG   |apscheduler.scheduler           |Looking for jobs to run|
23/09/2020 13:51:30|INFO    |apscheduler.scheduler           |Added job "Upgrade previously downloaded Subtitles" to job store "default"|
23/09/2020 13:51:30|DEBUG   |apscheduler.scheduler           |Next wakeup is due at 2020-09-23 13:52:30.624073+03:00 (in 59.982971 seconds)|
23/09/2020 13:51:30|DEBUG   |apscheduler.scheduler           |Looking for jobs to run|
23/09/2020 13:51:30|DEBUG   |apscheduler.scheduler           |Next wakeup is due at 2020-09-23 13:52:16.642082+03:00 (in 45.996102 seconds)|
23/09/2020 13:51:31|INFO    |engineio.server                 |9cc5c8c0eda14adeac94be04ff20cca3: Received packet MESSAGE data 1|
23/09/2020 13:51:31|INFO    |engineio.server                 |9cc5c8c0eda14adeac94be04ff20cca3: Received packet CLOSE data None|
23/09/2020 13:51:31|INFO    |engineio.server                 |110080cbeff3468d91d903a6efc31898: Sending packet OPEN data {'sid': '110080cbeff3468d91d903a6efc31898', 'upgrades': [], 'pingTimeout': 60000, 'pingInterval': 25000}|
23/09/2020 13:51:31|INFO    |engineio.server                 |110080cbeff3468d91d903a6efc31898: Sending packet MESSAGE data 0|
23/09/2020 13:51:32|INFO    |engineio.server                 |110080cbeff3468d91d903a6efc31898: Received packet MESSAGE data 1|
23/09/2020 13:51:32|INFO    |engineio.server                 |110080cbeff3468d91d903a6efc31898: Received packet CLOSE data None|
23/09/2020 13:51:32|INFO    |engineio.server                 |17affa2321d748ae88f42c2ad0458acd: Sending packet OPEN data {'sid': '17affa2321d748ae88f42c2ad0458acd', 'upgrades': [], 'pingTimeout': 60000, 'pingInterval': 25000}|
23/09/2020 13:51:32|INFO    |engineio.server                 |17affa2321d748ae88f42c2ad0458acd: Sending packet MESSAGE data 0|
23/09/2020 13:51:33|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): synobeast:8989|
23/09/2020 13:51:33|DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on synobeast|
23/09/2020 13:51:33|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): synobeast:8989|
23/09/2020 13:51:33|DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on synobeast|
23/09/2020 13:51:33|DEBUG   |urllib3.connectionpool          |http://synobeast:8989 "GET /api/MediaCover/12/poster-500.jpg?apikey=********ee HTTP/1.1" 200 None|
23/09/2020 13:51:33|DEBUG   |urllib3.connectionpool          |http://synobeast:8989 "GET /api/MediaCover/12/fanart.jpg?apikey=********ee HTTP/1.1" 200 None|
23/09/2020 13:51:34|DEBUG   |root                            |BAZARR Manually searching subtitles for this file: /tv/Raised by Wolves (2020)/Season 1/Raised by Wolves (2020) S01E07 Faces (1080p HMAX Webrip x265 10bit AC3 5.1 - Goki)[TAoE].mkv|
23/09/2020 13:51:34|DEBUG   |subzero.video                   |Parsing video: Raised by Wolves (2020) S01E07 Faces (1080p HMAX Webrip x265 10bit AC3 5.1 - Goki)[TAoE].mkv, hints: {'title': 'Raised by Wolves (2020)', 'type': 'episode'}|
23/09/2020 13:51:34|INFO    |subliminal_patch.core           |Determining basic video properties for 'Raised by Wolves (2020) S01E07 Faces (1080p HMAX Webrip x265 10bit AC3 5.1 - Goki)[TAoE].mkv' in '/tv/Raised by Wolves (2020)/Season 1'|
23/09/2020 13:51:34|DEBUG   |subliminal_patch.core           |GuessIt found: {
    "title": "Raised by Wolves (2020)",
    "season": 1,
    "episode": 7,
    "episode_title": "Faces",
    "screen_size": "1080p",
    "source": "Web",
    "other": "Rip",
    "video_codec": "H.265",
    "color_depth": "10-bit",
    "audio_codec": "Dolby Digital",
    "audio_channels": "5.1",
    "release_group": "Goki)[TAoE]",
    "container": "mkv",
    "type": "episode"
}|
23/09/2020 13:51:34|DEBUG   |subliminal_patch.core           |Size is 943491468|
23/09/2020 13:51:34|DEBUG   |subliminal_patch.core           |Computed hashes {'opensubtitles': 'b9788da78838237e'}|
23/09/2020 13:51:34|DEBUG   |root                            |BAZARR FFprobe used is /usr/bin/ffprobe|
23/09/2020 13:51:34|DEBUG   |root                            |FFprobe found: OrderedDict([('path', '/tv/Raised by Wolves (2020)/Season 1/Raised by Wolves (2020) S01E07 Faces (1080p HMAX Webrip x265 10bit AC3 5.1 - Goki)[TAoE].mkv'), ('duration', datetime.timedelta(seconds=2934, microseconds=48000)), ('size', 943491468), ('bit_rate', 2572531), ('container', 'mkv'), ('video', [OrderedDict([('id', 0), ('name', 'Encoded by Goki for TAoE using Shinguru V2.4'), ('width', 1920), ('height', 1080), ('scan_type', 'Progressive'), ('aspect_ratio', 1.778), ('pixel_aspect_ratio', 1.0), ('resolution', '1080p'), ('frame_rate', 23.976), ('codec', 'H.265'), ('profile', 'Main 10'), ('default', True)])]), ('audio', [OrderedDict([('id', 1), ('language', <Language [en]>), ('codec', 'AC-3'), ('channels_count', 6), ('channels', '5.1'), ('bit_rate', 384000), ('sampling_rate', 48000), ('default', True)])]), ('subtitle', [OrderedDict([('id', 2), ('language', <Language [en]>), ('format', 'SubRip')])]), ('provider', {'name': 'ffmpeg', 'version': {'/usr/bin/ffprobe': 'v4.3.1'}})])|
23/09/2020 13:51:34|DEBUG   |root                            |BAZARR is using these video object properties: {'name': '/tv/Raised by Wolves (2020)/Season 1/Raised by Wolves (2020) S01E07 Faces (1080p HMAX Webrip x265 10bit AC3 5.1 - Goki)[TAoE].mkv', 'source': 'Web', 'release_group': 'Goki)[TAoE]', 'resolution': '1080p', 'video_codec': 'H.265', 'audio_codec': 'Dolby Digital', 'imdb_id': None, 'hashes': {'opensubtitles': 'b9788da78838237e'}, 'size': 943491468, 'subtitle_languages': set(), 'original_name': 'Raised by Wolves (2020) S01E07 Faces (1080p HMAX Webrip x265 10bit AC3 5.1 - Goki)[TAoE].mkv', 'plexapi_metadata': {}, 'hints': {'title': 'Raised by Wolves (2020)', 'type': 'episode', 'single_value': True, 'expected_title': ['Raised by Wolves (2020)']}, 'audio_languages': {'eng'}, 'external_subtitle_languages': set(), 'series': 'Raised by Wolves ', 'season': 1, 'episode': 7, 'title': 'Faces', 'year': None, 'original_series': True, 'tvdb_id': None, 'series_tvdb_id': 368643, 'series_imdb_id': None, 'alternative_series': ['A farkas gyermekei'], 'used_scene_name': True, 'original_path': '/tv/Raised by Wolves (2020)/Season 1/Raised by Wolves (2020) S01E07 Faces (1080p HMAX Webrip x265 10bit AC3 5.1 - Goki)[TAoE].mkv', 'fps': 23.976}|
23/09/2020 13:51:34|INFO    |subliminal_patch.core           |Listing subtitles for <Episode ['Raised by Wolves ', 1x7]>|
23/09/2020 13:51:34|INFO    |subliminal_patch.core           |Listing subtitles with provider 'greeksubtitles' and languages {<Language [el]>}|
23/09/2020 13:51:34|INFO    |subliminal_patch.core           |Initializing provider greeksubtitles|
23/09/2020 13:51:34|DEBUG   |subliminal_patch.providers.greeksubtitles|Searching subtitles 'Raised by Wolves  S01E07'|
23/09/2020 13:51:34|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): gr.greek-subtitles.com:80|
23/09/2020 13:51:34|DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on gr.greek-subtitles.com|
23/09/2020 13:51:35|DEBUG   |urllib3.connectionpool          |http://gr.greek-subtitles.com:80 "GET /search.php?name=Raised%20by%20Wolves%20%20S01E07 HTTP/1.1" 200 4460|
23/09/2020 13:51:35|DEBUG   |subliminal_patch.providers.greeksubtitles|Found subtitle <GreekSubtitlesSubtitle 'http://subtitles.gr/subtitles/Raised-by-Wolves-2020-S01E07-Faces-1080p-HMAX-WEB-DL-DD5-1-H-264-NTG-/2681519/' [el:None]>|
23/09/2020 13:51:35|DEBUG   |subliminal_patch.providers.greeksubtitles|Found subtitle <GreekSubtitlesSubtitle 'http://subtitles.gr/subtitles/Raised-by-Wolves-S01E07-WEBRip-x264-ION10-/2681313/' [el:None]>|
23/09/2020 13:51:35|DEBUG   |subliminal_patch.providers.greeksubtitles|Searching subtitles 'A farkas gyermekei S01E07'|
23/09/2020 13:51:35|DEBUG   |urllib3.connectionpool          |http://gr.greek-subtitles.com:80 "GET /search.php?name=A%20farkas%20gyermekei%20S01E07 HTTP/1.1" 200 4218|
23/09/2020 13:51:35|INFO    |subliminal_patch.core           |Listing subtitles with provider 'opensubtitles' and languages {<Language [el]>, <Language [el]>}|
23/09/2020 13:51:35|INFO    |subliminal_patch.core           |Initializing provider opensubtitles|
23/09/2020 13:51:35|DEBUG   |subliminal_patch.providers.opensubtitles|Using timeout: 15|
23/09/2020 13:51:35|DEBUG   |subliminal_patch.providers.opensubtitles|Using HTTPS connection|
23/09/2020 13:51:35|DEBUG   |subliminal_patch.providers.opensubtitles|Using previous login token: 'hVMwvYjuhFXXXXXXXXXXXXXXXXX'|
23/09/2020 13:51:35|INFO    |subliminal_patch.providers.opensubtitles|Searching subtitles [{'moviehash': 'b9788da78838237e', 'moviebytesize': '943491468', 'sublanguageid': 'ell,ell'}, {'query': 'Raised by Wolves ', 'season': 1, 'episode': 7, 'sublanguageid': 'ell,ell'}, {'query': 'A farkas gyermekei', 'season': 1, 'episode': 7, 'sublanguageid': 'ell,ell'}]|
23/09/2020 13:51:35|DEBUG   |urllib3.connectionpool          |Starting new HTTPS connection (1): api.opensubtitles.org:443|
23/09/2020 13:51:35|DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on api.opensubtitles.org|
23/09/2020 13:51:35|DEBUG   |urllib3.connectionpool          |https://api.opensubtitles.org:443 "POST /xml-rpc HTTP/1.1" 200 191|
23/09/2020 13:51:35|INFO    |subliminal_patch.providers.opensubtitles|No subtitles found|
23/09/2020 13:51:35|INFO    |subliminal_patch.core           |Skipping provider 'subs4free': not a valid video|
23/09/2020 13:51:35|INFO    |subliminal_patch.core           |Listing subtitles with provider 'subs4series' and languages {<Language [el]>}|
23/09/2020 13:51:35|INFO    |subliminal_patch.core           |Initializing provider subs4series|
23/09/2020 13:51:35|DEBUG   |subliminal_patch.providers.subs4series|Getting show link|
23/09/2020 13:51:35|INFO    |subliminal_patch.providers.subs4series|Getting the subtitle list of show id raised-by-wolves/se08669ee03|
23/09/2020 13:51:35|DEBUG   |urllib3.connectionpool          |Starting new HTTPS connection (1): www.subs4series.com:443|
23/09/2020 13:51:35|DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on www.subs4series.com|
23/09/2020 13:51:35|DEBUG   |urllib3.connectionpool          |https://www.subs4series.com:443 "GET /tv-series/raised-by-wolves/se08669ee03/season-1/episode-7 HTTP/1.1" 200 None|
23/09/2020 13:51:35|DEBUG   |subliminal_patch.providers.subs4series|Found subtitle <Subs4SeriesSubtitle 'https://www.subs4series.com/tv-series/raised-by-wolves/se08669ee03/season-1/episode-7' [el:None]>|
23/09/2020 13:51:35|INFO    |subliminal_patch.core           |Listing subtitles with provider 'xsubs' and languages {<Language [el]>}|
23/09/2020 13:51:35|INFO    |subliminal_patch.core           |Initializing provider xsubs|
23/09/2020 13:51:35|INFO    |subliminal_patch.providers.xsubs|Logging in|
23/09/2020 13:51:35|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): xsubs.tv:80|
23/09/2020 13:51:35|DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on xsubs.tv|
23/09/2020 13:51:36|DEBUG   |urllib3.connectionpool          |http://xsubs.tv:80 "GET /xforum/account/signin/ HTTP/1.1" 200 2129|
23/09/2020 13:51:36|DEBUG   |urllib3.connectionpool          |http://xsubs.tv:80 "POST /xforum/account/signin/ HTTP/1.1" 302 0|
23/09/2020 13:51:36|DEBUG   |subliminal_patch.providers.xsubs|Logged in|
23/09/2020 13:51:36|DEBUG   |subliminal_patch.providers.xsubs|Getting show id|
23/09/2020 13:51:36|DEBUG   |subliminal_patch.providers.xsubs|Getting show id|
23/09/2020 13:51:36|DEBUG   |subliminal_patch.providers.xsubs|Getting show id|
23/09/2020 13:51:36|ERROR   |subliminal_patch.providers.xsubs|No show id found for 'Raised by Wolves ' ({'year': None})|
23/09/2020 13:51:36|INFO    |subliminal_patch.core           |Found 3 subtitle(s)|
23/09/2020 13:51:36|DEBUG   |subliminal.core                 |Terminating initialized providers|
23/09/2020 13:51:36|INFO    |subliminal_patch.core           |Terminating provider greeksubtitles|
23/09/2020 13:51:36|INFO    |subliminal_patch.core           |Terminating provider opensubtitles|
23/09/2020 13:51:36|INFO    |subliminal_patch.core           |Terminating provider subs4series|
23/09/2020 13:51:36|INFO    |subliminal_patch.core           |Terminating provider xsubs|
23/09/2020 13:51:36|INFO    |subliminal_patch.providers.xsubs|Logging out|
23/09/2020 13:51:37|DEBUG   |urllib3.connectionpool          |http://xsubs.tv:80 "GET /xforum/account/signout/ HTTP/1.1" 200 542|
23/09/2020 13:51:37|DEBUG   |subliminal_patch.providers.xsubs|Logged out|
23/09/2020 13:51:38|INFO    |subliminal_patch.score          |<GreekSubtitlesSubtitle 'http://subtitles.gr/subtitles/Raised-by-Wolves-2020-S01E07-Faces-1080p-HMAX-WEB-DL-DD5-1-H-264-NTG-/2681519/' [el:None]>: Computing score for video <Episode ['Raised by Wolves ', 1x7]> with {'hearing_impaired': False}|
23/09/2020 13:51:38|DEBUG   |subliminal_patch.score          |Adding title match equivalent|
23/09/2020 13:51:38|INFO    |subliminal_patch.score          |<GreekSubtitlesSubtitle 'http://subtitles.gr/subtitles/Raised-by-Wolves-2020-S01E07-Faces-1080p-HMAX-WEB-DL-DD5-1-H-264-NTG-/2681519/' [el:None]>: Computed score 252 with final matches {'resolution', 'season', 'source', 'series', 'audio_codec', 'episode', 'title'}|
23/09/2020 13:51:38|INFO    |subliminal_patch.score          |<GreekSubtitlesSubtitle 'http://subtitles.gr/subtitles/Raised-by-Wolves-S01E07-WEBRip-x264-ION10-/2681313/' [el:None]>: Computing score for video <Episode ['Raised by Wolves ', 1x7]> with {'hearing_impaired': False}|
23/09/2020 13:51:38|INFO    |subliminal_patch.score          |<GreekSubtitlesSubtitle 'http://subtitles.gr/subtitles/Raised-by-Wolves-S01E07-WEBRip-x264-ION10-/2681313/' [el:None]>: Computed score 247 with final matches {'series', 'source', 'episode', 'season'}|
23/09/2020 13:51:38|INFO    |subliminal_patch.score          |<Subs4SeriesSubtitle 'https://www.subs4series.com/tv-series/raised-by-wolves/se08669ee03/season-1/episode-7' [el:None]>: Computing score for video <Episode ['Raised by Wolves ', 1x7]> with {'hearing_impaired': False}|
23/09/2020 13:51:38|INFO    |subliminal_patch.score          |<Subs4SeriesSubtitle 'https://www.subs4series.com/tv-series/raised-by-wolves/se08669ee03/season-1/episode-7' [el:None]>: Computed score 342 with final matches {'resolution', 'year', 'season', 'series', 'source', 'audio_codec', 'episode'}|
23/09/2020 13:51:38|DEBUG   |root                            |BAZARR 3 Subtitles have been found for this file: /tv/Raised by Wolves (2020)/Season 1/Raised by Wolves (2020) S01E07 Faces (1080p HMAX Webrip x265 10bit AC3 5.1 - Goki)[TAoE].mkv|
23/09/2020 13:51:38|DEBUG   |root                            |BAZARR Ended searching Subtitles for this file: /tv/Raised by Wolves (2020)/Season 1/Raised by Wolves (2020) S01E07 Faces (1080p HMAX Webrip x265 10bit AC3 5.1 - Goki)[TAoE].mkv|
23/09/2020 13:51:40|DEBUG   |root                            |BAZARR Manually downloading Subtitles for this file: /tv/Raised by Wolves (2020)/Season 1/Raised by Wolves (2020) S01E07 Faces (1080p HMAX Webrip x265 10bit AC3 5.1 - Goki)[TAoE].mkv|
23/09/2020 13:51:40|DEBUG   |subzero.video                   |Parsing video: Raised by Wolves (2020) S01E07 Faces (1080p HMAX Webrip x265 10bit AC3 5.1 - Goki)[TAoE].mkv, hints: {'title': 'Raised by Wolves (2020)', 'type': 'episode'}|
23/09/2020 13:51:40|INFO    |subliminal_patch.core           |Determining basic video properties for 'Raised by Wolves (2020) S01E07 Faces (1080p HMAX Webrip x265 10bit AC3 5.1 - Goki)[TAoE].mkv' in '/tv/Raised by Wolves (2020)/Season 1'|
23/09/2020 13:51:40|DEBUG   |subliminal_patch.core           |GuessIt found: {
    "title": "Raised by Wolves (2020)",
    "season": 1,
    "episode": 7,
    "episode_title": "Faces",
    "screen_size": "1080p",
    "source": "Web",
    "other": "Rip",
    "video_codec": "H.265",
    "color_depth": "10-bit",
    "audio_codec": "Dolby Digital",
    "audio_channels": "5.1",
    "release_group": "Goki)[TAoE]",
    "container": "mkv",
    "type": "episode"
}|
23/09/2020 13:51:40|DEBUG   |subliminal_patch.core           |Size is 943491468|
23/09/2020 13:51:40|DEBUG   |subliminal_patch.core           |Computed hashes {}|
23/09/2020 13:51:40|DEBUG   |root                            |BAZARR FFprobe used is /usr/bin/ffprobe|
23/09/2020 13:51:40|DEBUG   |root                            |FFprobe found: OrderedDict([('path', '/tv/Raised by Wolves (2020)/Season 1/Raised by Wolves (2020) S01E07 Faces (1080p HMAX Webrip x265 10bit AC3 5.1 - Goki)[TAoE].mkv'), ('duration', datetime.timedelta(seconds=2934, microseconds=48000)), ('size', 943491468), ('bit_rate', 2572531), ('container', 'mkv'), ('video', [OrderedDict([('id', 0), ('name', 'Encoded by Goki for TAoE using Shinguru V2.4'), ('width', 1920), ('height', 1080), ('scan_type', 'Progressive'), ('aspect_ratio', 1.778), ('pixel_aspect_ratio', 1.0), ('resolution', '1080p'), ('frame_rate', 23.976), ('codec', 'H.265'), ('profile', 'Main 10'), ('default', True)])]), ('audio', [OrderedDict([('id', 1), ('language', <Language [en]>), ('codec', 'AC-3'), ('channels_count', 6), ('channels', '5.1'), ('bit_rate', 384000), ('sampling_rate', 48000), ('default', True)])]), ('subtitle', [OrderedDict([('id', 2), ('language', <Language [en]>), ('format', 'SubRip')])]), ('provider', {'name': 'ffmpeg', 'version': {'/usr/bin/ffprobe': 'v4.3.1'}})])|
23/09/2020 13:51:40|DEBUG   |root                            |BAZARR is using these video object properties: {'name': '/tv/Raised by Wolves (2020)/Season 1/Raised by Wolves (2020) S01E07 Faces (1080p HMAX Webrip x265 10bit AC3 5.1 - Goki)[TAoE].mkv', 'source': 'Web', 'release_group': 'Goki)[TAoE]', 'resolution': '1080p', 'video_codec': 'H.265', 'audio_codec': 'Dolby Digital', 'imdb_id': None, 'hashes': {}, 'size': 943491468, 'subtitle_languages': set(), 'original_name': 'Raised by Wolves (2020) S01E07 Faces (1080p HMAX Webrip x265 10bit AC3 5.1 - Goki)[TAoE].mkv', 'plexapi_metadata': {}, 'hints': {'title': 'Raised by Wolves (2020)', 'type': 'episode', 'single_value': True, 'expected_title': ['Raised by Wolves (2020)']}, 'audio_languages': {'eng'}, 'external_subtitle_languages': set(), 'series': 'Raised by Wolves ', 'season': 1, 'episode': 7, 'title': 'Faces', 'year': None, 'original_series': True, 'tvdb_id': None, 'series_tvdb_id': 368643, 'series_imdb_id': None, 'alternative_series': ['A farkas gyermekei'], 'used_scene_name': True, 'original_path': '/tv/Raised by Wolves (2020)/Season 1/Raised by Wolves (2020) S01E07 Faces (1080p HMAX Webrip x265 10bit AC3 5.1 - Goki)[TAoE].mkv', 'fps': 23.976}|
23/09/2020 13:51:40|INFO    |subliminal_patch.core           |Using 1 threads for 1 providers ({'subs4series'})|
23/09/2020 13:51:40|INFO    |subliminal_patch.core           |Downloading subtitle <Subs4SeriesSubtitle 'https://www.subs4series.com/tv-series/raised-by-wolves/se08669ee03/season-1/episode-7' [el:None]> with score 342|
23/09/2020 13:51:40|INFO    |subliminal_patch.core           |Downloading subtitle <Subs4SeriesSubtitle 'https://www.subs4series.com/tv-series/raised-by-wolves/se08669ee03/season-1/episode-7' [el:None]>|
23/09/2020 13:51:40|INFO    |subliminal_patch.core           |Initializing provider subs4series|
23/09/2020 13:51:40|INFO    |subliminal_patch.providers.subs4series|Downloading subtitle <Subs4SeriesSubtitle 'https://www.subs4series.com/tv-series/raised-by-wolves/se08669ee03/season-1/episode-7' [el:None]>|
23/09/2020 13:51:40|DEBUG   |urllib3.connectionpool          |Starting new HTTPS connection (1): www.subs4series.com:443|
23/09/2020 13:51:40|DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on www.subs4series.com|
23/09/2020 13:51:41|DEBUG   |urllib3.connectionpool          |https://www.subs4series.com:443 "GET /greek-subtitles/s42dce9537b/raised-by-wolves-s01e07-webrip-x264-ion10-720p1080p-hmax-web-dl-dd5-1-h-264-ntg-1080p-web-h264-videohole HTTP/1.1" 200 None|
23/09/2020 13:51:41|DEBUG   |urllib3.connectionpool          |https://www.subs4series.com:443 "GET /includes/anti-block-layover.php?launch=1 HTTP/1.1" 200 None|
23/09/2020 13:51:41|DEBUG   |urllib3.connectionpool          |https://www.subs4series.com:443 "GET /includes/anti-block.php HTTP/1.1" 200 None|
23/09/2020 13:51:41|DEBUG   |urllib3.connectionpool          |https://www.subs4series.com:443 "GET /getSub-tkMTYwMDg1ODMwMTAyMzAxNTUzMDQ2ODg3NDQ3NDI0.html HTTP/1.1" 302 None|
23/09/2020 13:51:41|DEBUG   |urllib3.connectionpool          |https://www.subs4series.com:443 "GET /greek-subtitles/s42dce9537b/raised-by-wolves-s01e07-webrip-x264-ion10-720p1080p-hmax-web-dl-dd5-1-h-264-ntg-1080p-web-h264-videohole HTTP/1.1" 200 None|
23/09/2020 13:51:41|ERROR   |subliminal_patch.subtitle       |PySRT-parsing failed, trying pysubs2|
23/09/2020 13:51:41|DEBUG   |subliminal_patch.subtitle       |Trying parsing with PySubs2|
23/09/2020 13:51:41|ERROR   |subliminal_patch.subtitle       |Couldn't convert subtitle <Subs4SeriesSubtitle 'https://www.subs4series.com/tv-series/raised-by-wolves/se08669ee03/season-1/episode-7' [el:windows-1253]> to .srt format: Traceback (most recent call last):  File "/app/bazarr/bazarr/../libs/subliminal_patch/subtitle.py", line 287, in is_valid    subs = pysubs2.SSAFile.from_string(text)  File "/app/bazarr/bazarr/../libs/pysubs2/ssafile.py", line 126, in from_string    return cls.from_file(fp, format_, fps=fps, **kwargs)  File "/app/bazarr/bazarr/../libs/pysubs2/ssafile.py", line 153, in from_file    format_ = autodetect_format(fragment)  File "/app/bazarr/bazarr/../libs/pysubs2/formats.py", line 67, in autodetect_format    raise FormatAutodetectionError("No suitable formats")pysubs2.exceptions.FormatAutodetectionError: No suitable formats|Traceback (most recent call last):  File "/app/bazarr/bazarr/../libs/subliminal_patch/subtitle.py", line 287, in is_valid    subs = pysubs2.SSAFile.from_string(text)  File "/app/bazarr/bazarr/../libs/pysubs2/ssafile.py", line 126, in from_string    return cls.from_file(fp, format_, fps=fps, **kwargs)  File "/app/bazarr/bazarr/../libs/pysubs2/ssafile.py", line 153, in from_file    format_ = autodetect_format(fragment)  File "/app/bazarr/bazarr/../libs/pysubs2/formats.py", line 67, in autodetect_format    raise FormatAutodetectionError("No suitable formats")pysubs2.exceptions.FormatAutodetectionError: No suitable formats|
23/09/2020 13:51:41|ERROR   |subliminal_patch.core           |Invalid subtitle|
23/09/2020 13:51:41|DEBUG   |subliminal.core                 |Terminating initialized providers|
23/09/2020 13:51:41|INFO    |subliminal_patch.core           |Terminating provider subs4series|
23/09/2020 13:51:42|DEBUG   |root                            |BAZARR Subtitles file downloaded for this file:/tv/Raised by Wolves (2020)/Season 1/Raised by Wolves (2020) S01E07 Faces (1080p HMAX Webrip x265 10bit AC3 5.1 - Goki)[TAoE].mkv|
23/09/2020 13:51:42|ERROR   |subliminal_patch.subtitle       |PySRT-parsing failed, trying pysubs2|
23/09/2020 13:51:42|DEBUG   |subliminal_patch.subtitle       |Trying parsing with PySubs2|
23/09/2020 13:51:42|ERROR   |subliminal_patch.subtitle       |Couldn't convert subtitle <Subs4SeriesSubtitle 'https://www.subs4series.com/tv-series/raised-by-wolves/se08669ee03/season-1/episode-7' [el:windows-1253]> to .srt format: Traceback (most recent call last):  File "/app/bazarr/bazarr/../libs/subliminal_patch/subtitle.py", line 287, in is_valid    subs = pysubs2.SSAFile.from_string(text)  File "/app/bazarr/bazarr/../libs/pysubs2/ssafile.py", line 126, in from_string    return cls.from_file(fp, format_, fps=fps, **kwargs)  File "/app/bazarr/bazarr/../libs/pysubs2/ssafile.py", line 153, in from_file    format_ = autodetect_format(fragment)  File "/app/bazarr/bazarr/../libs/pysubs2/formats.py", line 67, in autodetect_format    raise FormatAutodetectionError("No suitable formats")pysubs2.exceptions.FormatAutodetectionError: No suitable formats|Traceback (most recent call last):  File "/app/bazarr/bazarr/../libs/subliminal_patch/subtitle.py", line 287, in is_valid    subs = pysubs2.SSAFile.from_string(text)  File "/app/bazarr/bazarr/../libs/pysubs2/ssafile.py", line 126, in from_string    return cls.from_file(fp, format_, fps=fps, **kwargs)  File "/app/bazarr/bazarr/../libs/pysubs2/ssafile.py", line 153, in from_file    format_ = autodetect_format(fragment)  File "/app/bazarr/bazarr/../libs/pysubs2/formats.py", line 67, in autodetect_format    raise FormatAutodetectionError("No suitable formats")pysubs2.exceptions.FormatAutodetectionError: No suitable formats|
23/09/2020 13:51:42|ERROR   |root                            |BAZARR No valid Subtitles file found for this file: /tv/Raised by Wolves (2020)/Season 1/Raised by Wolves (2020) S01E07 Faces (1080p HMAX Webrip x265 10bit AC3 5.1 - Goki)[TAoE].mkv|NoneType: None|
23/09/2020 13:51:45|INFO    |engineio.server                 |17affa2321d748ae88f42c2ad0458acd: Received packet MESSAGE data 1|
23/09/2020 13:51:45|INFO    |engineio.server                 |17affa2321d748ae88f42c2ad0458acd: Received packet CLOSE data None|
23/09/2020 13:51:45|INFO    |engineio.server                 |27d23b86cc65459cbeed42ecf81dfc13: Sending packet OPEN data {'sid': '27d23b86cc65459cbeed42ecf81dfc13', 'upgrades': [], 'pingTimeout': 60000, 'pingInterval': 25000}|
23/09/2020 13:51:45|INFO    |engineio.server                 |27d23b86cc65459cbeed42ecf81dfc13: Sending packet MESSAGE data 0|
`

**Comment by morpheus65535** [comment]
It's still the same issue: Bazarr can't convert the subtitles file to srt because it's not a subtitles file. It's probably some redirection triggered by captcha protection. Nothing to do until someone implement anti-captcha for this provider.

**Comment by morpheus65535** [comment]
I've made an attempt to fix this issue. I'm not sure if it's going to help but please test it in 0.9.0.8 and confirm.

**Comment by morpheus65535** [comment]
No news is good news! If there's still an issue, please re-open this issue or open a new one.

**Comment by zzecool** [comment]
I just checked the history and it is working just fine thank you :)


-------- Original message --------

**Comment by morpheus65535** [comment]
> I just checked the history and it is working just fine thank you :)

Thanks!

**Comment by zzecool** [comment]
Hello there,

Its seems the problem with subs4free is back as I'm getting 0 size .srt downloaded.
I don't know if it is because of captcha or not.

Thank you.

**Comment by zzecool** [comment]
I see, thank you morph
