### ISSUE TITLE
[Provider] Subscene not working

### ISSUE THREAD

**Issue by pablorodriguezzurro** [morpheus65535/bazarr#1230]
Subscene provider error as seen in this log: https://pastebin.com/TRahxvqp

- OS: Windows-10-10.0.19041-SP0
- Bazarr: 0.9.0.7
- Python: 3.9.0

**Comment by Magikarplvl4** [comment]
This page is no longer available. It has either expired, been removed by its creator, or removed by one of the Pastebin staff.

**Comment by halali** [comment]
Python 3.9.0 is not supported.

**Comment by morpheus65535** [comment]
@halali didn't catch this but unfortunately I can reproduce the issue with 3.8.x.

**Comment by morpheus65535** [comment]
Just tested again and it seems to be working now. Can somebody else test it?

**Comment by pablorodriguezzurro** [comment]
Unexpected error in provider 'subscene': Traceback (most recent call last): File "c:\programdata\bazarr-anime\bazarr\../libs\subliminal_patch\core.py", line 170, in list_subtitles_provider results = self[provider].list_subtitles(video, provider_languages) File "c:\programdata\bazarr-anime\bazarr\../libs\subliminal_patch\providers\subscene.py", line 241, in list_subtitles return [s for s in self.query(video) if s.language in languages] File "c:\programdata\bazarr-anime\bazarr\../libs\subliminal_patch\providers\subscene.py", line 318, in query film = self.do_search(term, session=self.session, release=False, throttle=self.search_throttle) File "c:\programdata\bazarr-anime\bazarr\../libs\subliminal_patch\providers\subscene.py", line 292, in do_search return search(*args, **kwargs) File "c:\programdata\bazarr-anime\bazarr\../libs\subscene_api\subscene.py", line 285, in search soup = soup_for("%s/subtitles/%s" % (SITE_DOMAIN, endpoint), data={"query": term}, File "c:\programdata\bazarr-anime\bazarr\../libs\subscene_api\subscene.py", line 72, in soup_for ret = session.post(url, data=data) File "c:\programdata\bazarr-anime\bazarr\../libs\subliminal_patch\http.py", line 234, in post return self.retry_method("post", *args, **kwargs) File "c:\programdata\bazarr-anime\bazarr\../libs\subliminal_patch\http.py", line 217, in retry_method return retry_call(getattr(super(RetryingSession, self), method), fargs=args, fkwargs=kwargs, tries=3, delay=5, File "c:\programdata\bazarr-anime\bazarr\../libs\retry\api.py", line 101, in retry_call return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter, logger) File "c:\programdata\bazarr-anime\bazarr\../libs\retry\api.py", line 33, in __retry_internal return f() File "c:\programdata\bazarr-anime\bazarr\../libs\requests\sessions.py", line 581, in post return self.request('POST', url, data=data, json=json, **kwargs) File "c:\programdata\bazarr-anime\bazarr\../libs\subliminal_patch\http.py", line 60, in request return super(TimeoutSession, self).request(method, url, *args, **kwargs) File "c:\programdata\bazarr-anime\bazarr\../libs\subliminal_patch\http.py", line 165, in request ret = self._request(method, url, *args, **kwargs) File "c:\programdata\bazarr-anime\bazarr\../libs\subliminal_patch\http.py", line 99, in _request CloudScraper.request(self, 'GET', resp.url) File "c:\programdata\bazarr-anime\bazarr\../libs\cloudscraper\__init__.py", line 154, in request resp = self.sendChallengeResponse(resp, **kwargs) File "c:\programdata\bazarr-anime\bazarr\../libs\cloudscraper\__init__.py", line 187, in sendChallengeResponse sleep(self.delay)TypeError: an integer is required (got type NoneType)
--

Now this error is appearing

**Comment by pablorodriguezzurro** [comment]
https://pastebin.com/ev1kqH1y 

Now this error appears 

TypeError: an integer is required (got type NoneType)

**Comment by morpheus65535** [comment]
> https://pastebin.com/ev1kqH1y
> 
> Now this error appears
> 
> TypeError: an integer is required (got type NoneType)

Try emptying your cache directory: %programdata%\Bazarr\cache

**Comment by pablorodriguezzurro** [comment]
Done and no change

**Comment by pablorodriguezzurro** [comment]
After downgrading python to 3.8.7 seems to be working correctly :) Sorry to bother you.

**Comment by mrnutsen** [comment]
Still getting this error, tried python version 3..8.7, no difference. 

Switched to Debian 10 LXC, python 3.7.3, still no go. 

Error from log: [https://pastebin.com/zVfqKY7p](https://pastebin.com/zVfqKY7p)


Bazarr Version:
0.9.0.8
Sonarr Version:
3.0.4.1093
Radarr Version:
3.0.1.4259
Operating System:
Linux-5.4.78-2-pve-x86_64-with-debian-10.7
Python Version:
3.7.3
Bazarr Directory:
/opt/bazarr
Bazarr Config Directory:
/opt/bazarr/data

**Comment by morpheus65535** [comment]
You can try to empty `/opt/bazarr/data/cache`.

**Comment by mrnutsen** [comment]
Tried rm -r /opt/bazarr/data/cache/* , restarted bazarr, still the same problem.

**Comment by morpheus65535** [comment]
@pannal the issue is back... I need your help mate.

**Comment by mrnutsen** [comment]
Subscene now works almost all the time. Have made no changes to my setup, just let it run for some time.
I still get the error message randomly, but it mostly works now. 

makes me think it might not be a problem with bazarr, but the subscene site, it has been slow and unresponsive lately.

But, as for this issue, i think you can close it again. thanks for helping.

Bazarr Version:
0.9.0.8
Sonarr Version:
3.0.4.1093
Radarr Version:
3.0.1.4259
Operating System:
Linux-5.4.78-2-pve-x86_64-with-glibc2.28
Python Version:
3.8.7
Bazarr Directory:
/opt/bazarr
Bazarr Config Directory:
/opt/bazarr/data

**Comment by morpheus65535** [comment]
Let's close it again...
