### ISSUE TITLE
Legendasdivx provider not working (only for Series)

### ISSUE THREAD

**Issue by joaofilipedg** [morpheus65535/bazarr#1252]
I have only started using Bazarr in the past week, and during that time, while the Legendasdivx works on Movies (both for PT and PT-BR languages), it has never worked for Series. I noticed this because in the statistics I saw that there were a lot of movies that used this provider, while for Series there were none.

When trying to debug this behavior I found there might be two different issues:

1. Provider finds a matching subtitle in the logs, but reports as finding none:
https://pastebin.com/0a48N1ds

2. Provider actually doesn't find any subtitle when it should:
Here I even tested with searching only with PT and with both PT and PT-BR:
2.1. Only PT: https://pastebin.com/qEDGhxhb
2.2. PT + PT-BR: https://pastebin.com/xgz8sEry (here it seems Bazarr actually never even searches for PT subtitles)
Screenshot of the matching subtitles on Legendasdivx website:
https://imgur.com/2Lg4co0

I saw [this]( https://github.com/morpheus65535/bazarr/issues/1104) past issue, which might be related to the 2nd issue I mentioned, but it is apparently not fixed.

Software:
 - Bazarr: v0.9.0.8 
 - Radarr v3.0.2.4369
 - Sonarr v3.0.4.1091
 - OS: Ubuntu 20.10

**Comment by morpheus65535** [comment]
Sorry if you have issue with this provider but I don't have an account with them and I'm unable to create one. If you can share yours for debugging purpose, come see me on Discord.

**Comment by morpheus65535** [comment]
Should be fixed with my latest commit to v0.9.1 in dev branch. Can you confirm?

**Comment by joaofilipedg** [comment]
Thanks for the quick support!

Unfortunately, I am still seeing problems in the two referred situations. From looking at the requests, it seems to me that there are two issues:

1. When looking for both PT and PB subtitles (in this case PT should have 0 matches, but PB should have 1 match), Bazarr performs the following requests in order:
First, it searches for the PT subtitle for the specific episode:
 `"GET /modules.php?name=Downloads&file=jz&d_op=search&op=_jz00&query=%2522Mr.%2520Mayor%2520S01E02%2522&form_cat=28 HTTP/1.1"`
Then Bazarr looks for the PT subtitles for the season:
`"GET /modules.php?name=Downloads&file=jz&d_op=search&op=_jz00&query=%2522Mr.%2520Mayor%2520S01%2522&form_cat=28 HTTP/1.1"`
And finally when the intended behaviour I believe would be for Bazarr to look for the PB subtitles for the specific episode, the request includes both the PT and PB tags, messing with the results. Additionally, the request now has now information on the episode number:
`"GET /modules.php?name=Downloads&file=jz&d_op=search&op=_jz00&query=%2522Mr.%2520Mayor%2520S01%2522&form_cat=28&form_cat=29 HTTP/1.1"`
These requests were taken from [Log 1](https://pastebin.com/HRRbcQLc).

2. The second issue which can be seen from [Log 2](https://pastebin.com/knHrcCnF) is that, even when the first search for the PT subtitles should result in a match, Bazarr still doesn't find the subtitles. When comparing the request from Bazarr, with one I would do manually, I see that the %2522 tags are affecting the results.
Bazarr request, resulting in 0 matches:
`"GET /modules.php?name=Downloads&file=jz&d_op=search&op=_jz00&query=%2522Atlanta%2520S02E11%2522&form_cat=28 HTTP/1.1"`
My request resulting in a match:
`GET /modules.php?name=Downloads&file=jz&d_op=search&op=_jz00&query=atlanta%2520s02e11&form_cat=28 HTTP/1.1`

**Comment by morpheus65535** [comment]
Let me know if the latest fix is covering everything. Thanks for testing out!

**Comment by joaofilipedg** [comment]
I can confirm that both of the reported issues are now fixed. 

Thanks!
