### ISSUE TITLE
Task "Search for wanted Movies Subtitles" donwloads all missing subtitles

### ISSUE THREAD

**Issue by andrsm** [morpheus65535/bazarr#1458]
**Describe the bug**
The task "Search for wanted Movies Subtitles" looks for all missing subtitles. I have on only "download only monitored" in radarr settings and my wanted list is empty. But still bazarr starts downloading lots of subtitles.

The log is also full of line like this:
BAZARR Search is not active for this Movie /pathtomive/Movie (1999)/Moive.1999.1080p.BluRay.DTS.x264-SHDAD.mkv Language: en

**To Reproduce**
Run task "Search for wanted Movies Subtitles"

**Expected behavior**
It should not download anything.

**Software (please complete the following information):**
 - Bazarr: [e.g. v 0.9.6-beta.36]
 - Radarr version [e.g. v 3.2.2.5080]
 - Sonarr version [e.g. v 3.0.6.1265]
 - OS: [e.g. Ubnuntu 20.04]

**Comment by morpheus65535** [comment]
Fixed by https://github.com/morpheus65535/bazarr/commit/ae475f283e0cff87a057727345aef44c48ccf19f. Can you test and confirm in upcoming beta?

**Comment by andrsm** [comment]
It's a bit better, the task popup show 1/1 (as 1 is on the wanted list), but in the debuglog it still searches for subtitles. So the problem is still there.
When I run the task for series, it exits the job right away.

**Comment by morpheus65535** [comment]
I can't reproduce anymore with beta.37.

Send me your zipped config directory in PM on Discord and I'll try to reproduce with it.

**Comment by morpheus65535** [comment]
It should now be fixed. I was querying DB again but without excluding properly. Can you test and confirm please?

**Comment by andrsm** [comment]
Looks good here. Bazarr is not searching for anything if I have no movies monitored and if I set a movie to monitored bazarr searches for subtitles.

**Comment by morpheus65535** [comment]
Good news, thanks!
