### ISSUE TITLE
Cant find asian show/kdrama subtitle in subscene

### ISSUE THREAD

**Issue by makeran218** [morpheus65535/bazarr#1510]
**Describe the bug**
It seem bazarr cant find any subtitle for asian show in subscene. 
Here is the log https://raw.githubusercontent.com/makeran218/logs/main/bazarr.log

**To Reproduce**
1. Using manual or automatic subtitle search.

**Expected behavior**
Using manual or automatic subtitle search still cant find any subtitle. As you can see in the screenshot, the subtitle is available.

**Screenshots**
![image](https://user-images.githubusercontent.com/70996422/130023319-857d2dad-b073-4a47-a00c-185b337f8328.png)

**Software**
Bazarr Version
0.9.7
Sonarr Version
3.0.6.1265
Radarr Version
3.2.2.5080
Operating System
Linux-5.11.0-25-generic-x86_64-with-glibc2.29
Python Version
3.8.10

**Comment by morpheus65535** [comment]
This issue is frequent on Subscene for first season of new series. They don't add /First Season" to the series page until a second season is released. I will try to see if I can do something about it.

**Comment by morpheus65535** [comment]
Should be fixed in upcoming 0.9.8-beta.7.

**Comment by morpheus65535** [comment]
No news, good news.

**Comment by makeran218** [comment]
Sorry just checked today using the beta version 0.9.8
Some of the series or episode still cant find some subtitle.
Some episode ( Police University S01 E05) with language ID was shown from manual search not automatic search. But he EN language still not shown.

And for other show eg. The Penthouse S03E12, still no subs found
![image](https://user-images.githubusercontent.com/70996422/131389715-c11202b2-bca9-4213-9108-327f49202d7a.png)

Here is all the logs
https://raw.githubusercontent.com/makeran218/logs/main/bazarr2.log

Bazarr Version
0.9.8-beta.12
Sonarr Version
3.0.6.1265
Radarr Version
3.2.2.5080
Operating System
Linux-5.11.0-25-generic-x86_64-with-glibc2.29
Python Version
3.8.10

**Comment by morpheus65535** [comment]
You can try to empty your config/cache directory and try again. Also, when submitting a debug log, reduce the provider to the strict minimum to limit the number of lines in the log.

**Comment by makeran218** [comment]
I already clear the config and cache. For the Police University its working fine now.
But for the penthouse series, it still cant find anything from the subscene.
Here is the log https://raw.githubusercontent.com/makeran218/logs/main/bazarr3.log
![image](https://user-images.githubusercontent.com/70996422/131495243-5d2e83b5-5348-447d-b5bf-0b3236a4d0c3.png)

Maybe because the different naming title in subscene?

**Comment by morpheus65535** [comment]
Yes exactly, the title doesn't match so there's no way for Bazarr to assume it's the same title. Subscene searching is so limited that we can't even search by imdb id. :-/

**Comment by makeran218** [comment]
Its all good. Thanks for the helps :+1:
