### ISSUE TITLE
Unable to mass edit language profile for radarr and sonarr

### ISSUE THREAD

**Issue by sho-87** [morpheus65535/bazarr#1533]
**Describe the bug**
When I click mass edit and select all movies/TV shows, changing the profile to the one I created and saving doesn't seem to do anything. This is confirmed when clicking on the movie/TV show and seeing that no language profile has been set for any of them

When I try to set the language profile for a single movie/TV show, it seems to work correctly and I gain access to all the subtitle search features

Log: [bazarr.log](https://github.com/morpheus65535/bazarr/files/7134568/bazarr.log)

**To Reproduce**
1. Install Bazarr through unraid docker. Image: https://hub.docker.com/r/linuxserver/bazarr
2. Create language profile
3. Enable Sonarr and Radarr integration using the api key
4. Go to System > Tasks and run each of them once
5. Once tasks are all finished, Series and Movies screens are now populated
6. Go to either Series or Movies > Mass Edit > Select all > Change profile to English > Save.
7. Go back to Series/Movies, and there is nothing in the Languages Profile column

**Expected behavior**
Languages Profile column should say `English` for all movies/TV shows after mass edit

**Screenshots**
![language profile](https://user-images.githubusercontent.com/5199715/132644736-e05dc2b5-c8af-496d-ac73-5259cf4961b6.PNG)

**Software (please complete the following information):**
 - Bazarr: 0.9.8
 - Radarr version 3.2.2.5080
 - Sonarr version 3.0.6.1265
 - OS: Linux-5.10.28-Unraid-x86_64-with (running in a docker container on unraid)

**Comment by TRaSH-** [comment]
Fixed in the latest dev version
It's only a GUI issue, if you refresh the page it should show up.

**Comment by sho-87** [comment]
it seems to be more than a GUI issue. Ive tried refreshing, using a different device, restarting bazarr, but I still cant mass edit anything

**Comment by morpheus65535** [comment]
However, it's fixed in 0.9.9-beta

**Comment by RuneMason1** [comment]
This issue seems to have reared its head again

**Comment by anderson-oki** [comment]
@RuneMason1 

> This issue seems to have reared its head again

Can you provide some video of the issue?

**Comment by RuneMason1** [comment]
Here ya go. Also, not sure about dev console, not sure where to find that. 

https://github.com/morpheus65535/bazarr/assets/78815068/ca153d81-33d4-4ede-930a-02039ee207f2

**Comment by anderson-oki** [comment]
> Here ya go. Also, not sure about dev console, not sure where to find that.
> 
>  Recording.2024-06-11.220601.mp4

https://help.vivaldi.com/desktop/tools/developer-tools/ This is how you open it, can you check if you have some message.

**Comment by RuneMason1** [comment]
Oh, I was thinkin you meant a console in bazarr

**Comment by RuneMason1** [comment]
Not sure what i'm looking for in the dev tools. Is there a specific tab or section? the default is just a code elements viewer

**Comment by anderson-oki** [comment]
> Not sure what i'm looking for in the dev tools. Is there a specific tab or section? the default is just a code elements viewer

Console tab, check for any error message.

**Comment by RuneMason1** [comment]
Request entity too large is what it says to explain the 413 error.

**Comment by RuneMason1** [comment]
Is there any way to clear all the movies from bazarr, and rescan/re-sync and have the desired profile automatically assigned? Or something LIKE that? Like a default profile

**Comment by anderson-oki** [comment]
> Request entity too large is what it says to explain the 413 error.

This is fixed on the upcoming beta.

**Comment by RuneMason1** [comment]
Gotcha. is that available to grab now, or is it in the works?
