### ISSUE TITLE
[SUBDIVX.COM] Bazaar doesn't seem to find subs even if they exists (release_group error)

### ISSUE THREAD

**Issue by JMVS** [morpheus65535/bazarr#1675]
**Describe the bug**
Bazarr is not able to find matches within the configured providers even though the subtitles can be found via a manual search.

**To Reproduce**
1. Go to the series with missing subtitles
2. Click on Subtitlle search icon for the episode you want to
3. Look at the results, it shows several results and even if the release_group is there it doesn't show like it meets the release_group critaria.

**Expected behavior**
Bazaar should detect the release_group even if the release was targetted to multiple groups.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/7751148/148928183-f5b9dba3-330c-4b7e-a5ed-c648c9a5f767.png)
![imagen](https://user-images.githubusercontent.com/7751148/148927941-8fc40895-5af8-4ad3-88e9-08bf2cf1ba74.png)
![imagen](https://user-images.githubusercontent.com/7751148/148928075-971de237-9ec2-4943-b06e-aaf3bf6850da.png)

**Software (please complete the following information):**
 - Bazarr: 0.9.9
 - Radarr version 3.2.2.5080
 - Sonarr version 3.0.6.1342
 - OS: Docker on Ubunto Server 20.01

**Additional context**
Subtitles configured as: 1) LatAm Spanish, 2) Spanish
Logs attached (I know tusubtitulo had problems when I grabbed the logs, but see screenshoot.)
[bazarr.log](https://github.com/morpheus65535/bazarr/files/7845824/bazarr.log)
Providers for which I usually have this problem: tusubtitulo.com, subdivx.com 
In this case:
https://www.tusubtitulo.com/episodes/83736/seal-team-5x11-three-guns
https://www.subdivx.com/index.php?accion=5&buscar2=Seal+Team+S05E11&masdesc=&idusuario=&nick=&oxfecha=&oxcd=&oxdown=&pg=1

**Comment by TRaSH-** [comment]
To what did you set your scores

**Comment by JMVS** [comment]
> To what did you set your scores

If you mean "Automatic Subtitles Synchronization" the values are:
Series Score Threshold 85/100
Movies Score Threshold 70/100

If you meant something else, please clarify

**Comment by JMVS** [comment]
If the score is based on the total of attributes found I think I should be setting the Score at around 40% (meeting 6 items of the 14 listed). Seems awful low. Furthermore, I suppose it should be detecting the resolution in the case of subdivx.com (for which I don't know why is not showing as a possible match)

**Comment by vitiko98** [comment]
Thanks for your report. Before we address your bug:

1. Subdivx is broken in your version. It was fixed in d373bc8c0e936e8fecaf54cf2e122b0a0cfeca9f, only available on **beta** release at the moment. If you update Bazarr, you should see those results. Also note that Subdivx, for some reason, may be returning empty pages for some IPs.
2. Tusubtitulo was discontinued from Bazarr. See #1591.

There's an issue regarding Subdivx's release-group matching: the server returns the subtitle descriptions in lowercase if you are not logged in. This makes almost impossible for `subliminal_patch` and for `guessit` to match release groups. An alternative would be to match release group sub-strings in lowercase, but this would lead to a lot of false positives as release groups tend to be short strings. 

Sadly, there's nothing we can do to fix release groups for Subdivx. Remember that the fact that we try to guess release info from a plain text human-oriented description written by Subdivx users is already not so optimal for automated guessing.

**Comment by JMVS** [comment]
@vitiko98 Thanks for your reply.
1. I see. I'm using LSIO's Docker release. I'll have to wait until the fix is merged to the main branch and LSIO's image updated. I did update to the lastes LSIO's image availate at the time of writing: 1.0.2
2. Now that I've updated I can see TuSubtitulo being removed. Thanks for letting me know.

As per the SubDivX issue, I can see that when you're not logged in the results are lowercase, which raises two questions:
1. I'm not clear why matching to lowercase (or case insesitive for that matter) would be problematic. Bear in mind is a Spanish-driven community/website and the release group name's would barely resemble Spanish words that could create false positives.
2. Can a system be implemented where one can login to the Subdivx account from Bazarr? That would also solve the lowercase problem.

**Comment by JMVS** [comment]
Upon further investigation to Subdivx, if you set the following cookie for www.subdivx.com will show the description in the original case.
**iduser_cookie=VkZaRk9WQlJQVDA12809** _(pseudo-random generated)_

Private tab, no logged-in:
![imagen](https://user-images.githubusercontent.com/7751148/149027456-7196d6c1-0fa5-46a1-8946-5b908c549bfc.png)

**Comment by vitiko98** [comment]
> Sadly, there's nothing we can do to fix release groups for Subdivx

So I was wrong...

>     1. I'm not clear why matching to lowercase (or case insesitive for that matter) would be problematic. Bear in mind this is a Spanish-driven community/website and the release group name's would barely resemble any Spanish words that could create false positives AFAIK.
> 
>     2. Can a system be implemented where one can login to the Subdivx account from Bazarr? That would also solve the lowercase problem.

1. I see where you are coming from, but short strings in lowercase are still not safe (e.g. `DON`)
2. You already figured it out :laughing:

> Upon further investigation to Subdivx, if you set the following cookie for [www.subdivx.com](http://www.subdivx.com) will show the description in the original case. **iduser_cookie=VkZaRk9WQlJQVDA12809** _(pseudo-random generated)_

And what's more: it also give us the download URL in the results page! Without the cookie, we had to scrape the download URL. That's another blessing.

I've added a commit (8ad4ec95f98b5f22dd40dd681a3d42014ace62c1) with the brand new cookie stuff. The Subdivx provider should match release groups and download faster now. You can check it out in the **next** beta release (keep in mind these are released once a day).

Thanks!
