### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by TTLucian** [morpheus65535/bazarr#1857]
**Describe the bug**

Error in browser:
`
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
`

Error in browser console:
```
GET http://localhost:6767/ 500 (INTERNAL SERVER ERROR)
GET http://localhost:6767/favicon.ico 500 (INTERNAL SERVER ERROR)
```

Error in logs:
`
ERROR   |app.app                         |Exception on /favicon.ico [GET]|'Traceback (most recent call last):\n  File "c:\\data\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1516, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "c:\\data\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1492, in dispatch_request\n    self.raise_routing_exception(req)\n  File "c:\\data\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1474, in raise_routing_exception\n    raise request.routing_exception  # type: ignore\n  File "c:\\data\\bazarr\\bazarr\\../libs\\flask\\ctx.py", line 367, in match_request\n    result = self.url_adapter.match(return_rule=True)  # type: ignore\n  File "c:\\data\\bazarr\\bazarr\\../libs\\werkzeug\\routing.py", line 2041, in match\n    raise NotFound()\nwerkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "c:\\data\\bazarr\\bazarr\\../libs\\flask\\app.py", line 2073, in wsgi_app\n    response = self.full_dispatch_request()\n  File "c:\\data\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1518, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File "c:\\data\\bazarr\\bazarr\\../libs\\flask_restful\\__init__.py", line 271, in error_router\n    return original_handler(e)\n  File "c:\\data\\bazarr\\bazarr\\../libs\\flask_restful\\__init__.py", line 271, in error_router\n    return original_handler(e)\n  File "c:\\data\\bazarr\\bazarr\\../libs\\flask_restful\\__init__.py", line 271, in error_router\n    return original_handler(e)\n  [Previous line repeated 7 more times]\n  File "c:\\data\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1386, in handle_user_exception\n    return self.handle_http_exception(e)\n  File "c:\\data\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1326, in handle_http_exception\n    return self.ensure_sync(handler)(e)\nTypeError: page_not_found() takes 0 positional arguments but 1 was given'|
`

**Software (please complete the following information):**
 - Bazarr: v1.0.5-beta.17
 - OS: Windows 11

**Additional context**
Works fine if I reinstall Bazarr v1.0.4
Page stops working after updating to v1.0.5-beta.17 via Bazarr web interface (Tasks/Update Bazarr)

**Comment by morpheus65535** [comment]
I cannot reproduce. Make sur to refresh your browser.

**Comment by TTLucian** [comment]
I tried on several browsers (Edge, Chrome), removed all browsing data, on several devices (laptop, mobile and host system). Same result. Deleted the Bazarr folder, reinstalled by using Windows installer, updated via Bazarr interface to development branch (latest beta) three times. Same result every time, both through nginx proxy and direct connection (http://host:port and http://ip:port). Bazarr seems to be working but I cannot access the interface.

**Comment by morpheus65535** [comment]
Did you define a base url for Bazarr? If so try entering it yourself like this: http://ip:port/bazarr/

**Comment by TTLucian** [comment]
It works with /bazarr added to url (both nginx and direct host/ip). In previous versions there was no need to add this. 🤔 I will investigate further later tonight. Thanks a lot!

**Comment by TTLucian** [comment]
Yeah! Definitely something has changed. With previous versions I had "/bazarr" added as base url in config and all url's worked without the need to add /bazarr at the end.

With previous version I was able to use url's like this:
- http://ip:port
- https://bazarr.domain.com
- https://domain.com/bazarr

Now they only work like this:
- http://ip:port/bazarr
- https://bazarr.domain.com/bazarr
- https://domain.com/bazarr

I have removed /bazarr base url but url's like "https://domain.com/bazarr" do not work anymore.

Thanks!

**Comment by morpheus65535** [comment]
Are you able to confirm what's the latest version where it works as expected?

**Comment by TTLucian** [comment]
Yes. Works fine on the stable release v1.0.4. As for the betas, I'm not sure which version stopped working. Haven't accessed it for some time.

**Comment by daschy** [comment]
Same Internal Server Error with the following setup:
-  Raspbian GNU/Linux 10 (buster) 
- Bazarr v1.04 

I tried `http://[local network ip]:6767`

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta. Can you test and confirm please?

**Comment by TTLucian** [comment]
Hi. Sorry for the late reply. I've put back "bazarr" as base url. Login page shows but after clicking the login button it redirects at "https://bazarr/". Name does not resolve, of course. Login does occur and it works as expected but login button redirects to bogus address.
All links behave the same:

- http://ip:port/
- https://bazarr.domain.com/
- https://domain.com/bazarr

**Comment by LASER-Yi** [comment]
Should be fixed in the next upcoming beta version

**Comment by morpheus65535** [comment]
No news, good news!
