### ISSUE TITLE
subscence auth issue

### ISSUE THREAD

**Issue by beaverly72** [morpheus65535/bazarr#1884]
**Describe the bug**
Receive the following error when attempting to get subs with subscene as provider:
Throttling subscene for 10 minutes, until 22/06/26 07:04, because of: ProviderError. Exception info: 'Something went wrong when trying to log in #1'

Throttling subscene for 10 minutes, until 22/06/26 07:04, because of: ConfigurationError. Exception info: 'Username and password must be specified'

I have verified that the creds in my subscene provider do work when logging in at subscene.com.  reentered creds for bazaar provider, and continued to receive the same exception

**To Reproduce**
1. Setup provider for subscence with subscence creds
2. download subs of any movie
3. Go to System > Logs

**Expected behavior**
Auth to subscene should be successful since creds for provider have been verified manually

**Screenshots**
N/A

**Software (please complete the following information):**
 - Bazarr: 1.0.5-beta.35
 - Radarr version 4.1.0.6175
 - Sonarr version 3.0.8.1507
 - OS: linuxserver.io docker

**Additional context**
[bazarr.log](https://github.com/morpheus65535/bazarr/files/8986568/bazarr.log)

**Comment by EricHupp** [comment]
Also having this same problem.  Removed and readded provider and problem persists.

**Comment by vitiko98** [comment]
This issue might be related to provider configs updates (there's a conditional somewhere only for subscene configs).

I just made a commit (a748903dc4d8c73e30e4b642aae5534a09571477) that should fix this. Please test it in upcoming beta release.

**Comment by beaverly72** [comment]
It appears I am still receiving the error..

Throttling subscene for 10 minutes, until 22/07/03 06:27, because of: ProviderError. Exception info: 'Something went wrong when trying to log in #1'

possible this is on subscence's side?

Bazarr Version
1.1.1-beta.0
Package Version
v1.1.1-beta.0-ls362 by [linuxserver.io](https://linuxserver.io)
Sonarr Version
3.0.8.1507
Radarr Version
4.1.0.6175
Operating System
Linux-5.15.46-Unraid-x86_64-wit
[bazarr.log](https://github.com/morpheus65535/bazarr/files/9034631/bazarr.log)

**Comment by bozoweed** [comment]
still broken please remove login .....

Throttling subscene for 10 minutes, until 22/07/17 05:47, because of: ProviderError. Exception info: 'Something went wrong when trying to log in #1'

Bazarr Version
1.1.1-beta.5
Package Version
v1.1.1-beta.5-ls367 by [linuxserver.io](https://linuxserver.io)
Sonarr Version
3.0.8.1507
Radarr Version
4.1.0.6175
Operating System
Linux-5.10.0-15-amd64-x86_64-with
Python Version
3.9.5
Bazarr Directory
/app/bazarr/bin
Bazarr Config Directory
/config
Uptime
0d 00:06:47
Time Zone
Europe/Paris

**Comment by bozoweed** [comment]
fixed for me with v1.1.1-beta.6

 but an other bug is appear 

Throttling  subscene for 10 minutes, until 22/07/23 11:33, because of: HTTPError.  Exception info: '409 Client Error: Conflict for url:  https://subscene.com/subtitles/searchbytitle'
-- | --

what does that mean ?

**Comment by morpheus65535** [comment]
> but an other bug is appear
> 
> Throttling subscene for 10 minutes, until 22/07/23 11:33, because of: HTTPError. Exception info: '409 Client Error: Conflict for url: https://subscene.com/subtitles/searchbytitle' -- | --
> 
> what does that mean ?

No idea, if you can reproduce, please open a new issue with the complete debug log.

**Comment by morpheus65535** [comment]
@beaverly72 can you confirm if it's fixed in latest beta please?

**Comment by beaverly72** [comment]
I am still seeing the same provider exception "Throttling subscene for 10 minutes, until 22/07/27 21:24, because of: ProviderError. Exception info: 'Something went wrong when trying to log in #1'"

**Comment by morpheus65535** [comment]
@beaverly72 what anti-captcha provider are you using?

I'm trying to reproduce for 2 days and I can't. I've downloaded dozens of subtitles from subscene without any error. :-/

**Comment by kmt7** [comment]
same issue here: 
```
Throttling subscene for 10 minutes, until 22/08/13 21:45, because of: HTTPError. Exception info: '409 Client Error: Conflict for url: https://subscene.com/subtitles/searchbytitle'
```

 anti-captcha -> anti captcha

**Comment by thessem** [comment]
I am getting the same error. My guess is I am trying to search for en/en.forced/en.sdh subtitles simultaneously for each episode and the subscene rate limiter is kicking in

**Comment by morpheus65535** [comment]
> same issue here

this is unrelated to original issue. Open a dedicated issue with debug log while you reproduce the issue.

**Comment by morpheus65535** [comment]
No news, good news.
