### ISSUE TITLE
Job "Upgrade previously downloaded Subtitles (trigger: interval[12:00:00], next run at: 2022-07-16 01:36:27 CEST)" raised an exception

### ISSUE THREAD

**Issue by hunter-nl** [morpheus65535/bazarr#1909]
**Describe the bug**
Task running raised exception.
Job "Upgrade previously downloaded Subtitles (trigger: interval[12:00:00], next run at: 2022-07-16 01:36:27 CEST)" raised an exception

Traceback (most recent call last):
  File "/opt/Bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/opt/Bazarr/bazarr/subtitles/upgrade.py", line 69, in upgrade_subtitles
    int(upgradable_episode[\'score\'])
TypeError: int() argument must be a string, a bytes-like object or a number, not \'NoneType\

**To Reproduce**
Running task "Upgrade previously downloaded Subtitles"

**Expected behavior**
Running job fine without raising an exception

**Software (please complete the following information):**
 Bazarr Version 1.1.0
Sonarr Version 3.0.8.1507
Radarr Version 4.1.0.6175
Operating System Linux-4.18.0-372.13.1.el8_6.x86_64-x86_64-with-glibc2.2.5
Python Version 3.8.12

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta. Can you test and confirm please?

**Comment by hunter-nl** [comment]
I've upgraded to 1.1.1-beta.8. But issue still exist:
```Traceback (most recent call last):
  File "/opt/Bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/opt/Bazarr/bazarr/subtitles/upgrade.py", line 112, in upgrade_subtitles
    int(upgradable_movie[\'score\'])
TypeError: int() argument must be a string, a bytes-like object or a number, not \'NoneType\
```

Only difference is the line number in ```File "/opt/Bazarr/bazarr/subtitles/upgrade.py", line 112, in upgrade_subtitles```

**Comment by morpheus65535** [comment]
@hunter-nl my bad, I only did half of the job. It should be fine with beta.9.

**Comment by hunter-nl** [comment]
@morpheus65535 It is now solved with beta 9. Thank you!
