### ISSUE TITLE
can't upload manual subtitles; error: Exception on /api/episodes/subtitles [POST]

### ISSUE THREAD

**Issue by xloooolx** [morpheus65535/bazarr#2051]
**Describe the bug**
When manually uploading subtitles to episodes, I get an error, but on movies, it's working.

**To Reproduce**
1. Go to upload substitle with"srt or ass" extension
2. Click on upload
3. See error
Error 500 You have disconnected from the server

**Expected behavior**
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/bazarr/bin/bazarr/../libs/flask_restx/api.py", line 405, in wrapper
    resp = resource(*args, **kwargs)
  File "/app/bazarr/bin/bazarr/../libs/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/app/bazarr/bin/bazarr/../libs/flask_restx/resource.py", line 46, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/bazarr/bin/bazarr/api/utils.py", line 30, in wrapper
    return actual_method(*args, **kwargs)
  File "/app/bazarr/bin/bazarr/api/episodes/episodes_subtitles.py", line 148, in post
    result = manual_upload_subtitle(path=episodePath,
TypeError: manual_upload_subtitle() got an unexpected keyword argument \'sceneName\

**Software (please complete the following information):**
- Bazarr Version   1.1.5-beta.8
- Package Version  v1.1.5-beta.8-ls467 by linuxserver.io
- Sonarr Version  4.0.0.362
- Radarr Version  4.4.1.6918
-  Operating System  Linux-5.15.0-53-generic-x86_64-with

**Comment by halali** [comment]
Fixed in upcoming beta release

**Comment by xloooolx** [comment]
The problem came back again

Bazarr Version   1.1.5-beta.24

`
26/02/2023 13:57:00|ERROR   |app.app                         |Exception on /api/episodes/subtitles [POST]|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 1820, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "/app/bazarr/bin/bazarr/../libs/flask/app.py", line 1796, in dispatch_request\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n  File "/app/bazarr/bin/bazarr/../libs/flask_restx/api.py", line 405, in wrapper\n    resp = resource(*args, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/flask/views.py", line 107, in view\n    return current_app.ensure_sync(self.dispatch_request)(**kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/flask_restx/resource.py", line 46, in dispatch_request\n    resp = meth(*args, **kwargs)\n  File "/app/bazarr/bin/bazarr/api/utils.py", line 30, in wrapper\n    return actual_method(*args, **kwargs)\n  File "/app/bazarr/bin/bazarr/api/episodes/episodes_subtitles.py", line 148, in post\n    history_log(4, sonarrSeriesId, sonarrEpisodeId, result, fake_provider=provider, fake_score=score)\n  File "/app/bazarr/bin/bazarr/sonarr/history.py", line 10, in history_log\n    description = result.message\nAttributeError: \'tuple\' object has no attribute \'message\''|
`
