### ISSUE TITLE
Upgrade previously downloaded subtitles - continues to run upgrade even at 100% score

### ISSUE THREAD

**Issue by dcglabs** [morpheus65535/bazarr#2059]
When the upgrade previously downloaded subtitles runs, it appears to continually download subtitles for episodes even with socres of 100%.

Debug logs for episode upgrade run: https://pastebin.com/ESjM6Afc

This episode history:
![image](https://user-images.githubusercontent.com/5561155/218186118-f5008fbc-94b1-413c-b2dd-90d770e974d0.png)

**Software (please complete the following information):**
 - Bazarr: 1.1.5-beta13
 - Sonarr version 4.0.0.373
 - OS: debian 11

**Comment by morpheus65535** [comment]
I'm going to add some debug logging in the upgrade decision routine because right now we're very verbose on the search process but not enough on why we did it. I'll get back once it's ready to be released in next beta.

**Comment by dcglabs** [comment]
That sounds good. I looked over log myself didn't see any explicit reasoning behind upgrade decisions.

**Comment by halali** [comment]
Should be fixed in upcoming beta 1.1.5-beta.18

Please retest it

**Comment by tenfire** [comment]
I'm running 1.1.5-beta.19. Still happening for me. The last two upgrades happend on 1.1.5-beta.19.
![brave_e5ytq1dULs](https://user-images.githubusercontent.com/3463357/220343764-e9b30aca-0e04-48f2-a504-4287d03ce72d.png)

**Comment by tenfire** [comment]
Also happens for other scores than 100.0% for me:
![brave_tkce7knEN4](https://user-images.githubusercontent.com/3463357/220344701-b004b778-e9c7-4c49-ac9f-b20fb52114ea.png)

**Comment by halali** [comment]
what bazarr version ?

**Comment by MrBamse** [comment]
Im not sure if this is related because I can't see that I have the "upgrade" icon but I've noticed this on several shows (unsure regarding movies) lately.

The original 100% subtitle is replaced with a lower score subtitle for some reason.
Could this be related?

![image](https://user-images.githubusercontent.com/80944276/220909618-84058404-dff8-4ebb-8bf7-362c1acc49af.png)


![image](https://user-images.githubusercontent.com/80944276/220909756-dcc19928-a50e-458e-9070-12cb047ef6b0.png)

**Comment by morpheus65535** [comment]
> Could this be related?

No. Check if the filename for those file include accented characters.

**Comment by morpheus65535** [comment]
@dcglabs should be fixed by #2070 in upcoming beta. Can you test and confirm please?

**Comment by tenfire** [comment]
I have tested this for 2 days now, seems to be working and I am still getting normal upgrades.

**Comment by morpheus65535** [comment]
Let's keep it open for a couple of days but I'm happy to see that it seems to be working fine now!

**Comment by dcglabs** [comment]
I have it running. I am keeping eye on it, but doesn't seem to do continuous upgrades. However, I haven't seen anything upgrade now. That is not to say there is truly nothing to upgrade, but not sure how strict the upgrade logic is now. 

I have notice that pulling up history is extremely slow now. Both in main navigation History->Episodes | Movies | Statistics also in individual shows. Does seem the changes have made the history query slow.

**Comment by dcglabs** [comment]
Update on history loading time:

I realize now that the number of entries is insane ~50,000 for episodes and ~20,000 for movies. Those numbers really skyrocketed with the perpetual subtitles upgrade issue. I think the size of entries is the cause of drag on system loading. 

Any way to prune without losing download/upgrade history refence? Or limit query results on history view?

**Comment by halali** [comment]
i have 130 000 rows in history and load time isnt that bad, yes its not instant, and probably there can be some improvements but its not part of this issues...
also there is limit for one page...

Closing this as resolved

**Comment by AnilDaoud** [comment]
i have the same issue, with the 1.2.0 release

<img width="776" alt="image" src="https://user-images.githubusercontent.com/3533332/232219569-a63dedcb-ab01-4dd9-8d9e-6062a2c3dbc0.png">

**Comment by morpheus65535** [comment]
> i have the same issue, with the 1.2.0 release

No you don't. Those aren't upgrade but regular download. The subtitles file is probably not indexed once downloaded and Bazarr download it again. maybe related to #1961 .

**Comment by AnilDaoud** [comment]
you are correct

**Comment by jfrcom** [comment]
I am running 1.2.1 and seem to have the same issue with two movies in my library. 

<img width="779" alt="Bildschirmfoto 2023-05-09 um 10 15 34" src="https://user-images.githubusercontent.com/44551091/237036679-3699f215-5c4a-4576-ba76-5d9d014e7535.png">

Any help would be appreciated.
