### ISSUE TITLE
Throttling titlovi for 10 minutes, until 23/02/15 20:09, because of: AuthenticationError. Exception info: 'Login failed'

### ISSUE THREAD

**Issue by phpavelic** [morpheus65535/bazarr#2062]
Hello!
No matter what I do it ends up with this error, newly created account with only lowercase letters - tried "abcde" and "!@#$%" passwords with no success. Note that other providers are working flawlessly.

Are there any workarounds that I am missing?

Any help is appreciated.

**Comment by morpheus65535** [comment]
@phpavelic I've just tested and it works as expected. I don't know what's going wrong with your account. Can you provide debug log while searching for a single subtitles?

**Comment by JackTorrance1** [comment]
I have the same error with titlovi. I just wanted to say that the error happens after some time. Usually a week or so after creating new account.

**Comment by dusanzk** [comment]
> 

No, i'm not, It's been like this since day one for me, I've had Bazarr installed on three different devices at three completely seperate locations and they specifically told me, two times, that it was because of multiple requests in such a short time, they even gave an example of there being over 100 requests for a certain show within a 10 minute time frame. At the time they also told me that the developers of Bazarr could find all the information needed to access the Titlovi API at the following site: https://github.com/tturkalj/service.subtitles.titlovi-com-official.

The last information I have regarding Titlovi support is that one of their site admins or developers sent you a message directly through Discord.

**Comment by dusanzk** [comment]
Nikola Ristić (nikola.titlovi@gmail.com) is the person I was in contact with.

**Comment by daburger** [comment]
I am also getting the same issue but for opensubtitlescom:

`Throttling opensubtitlescom for 10 minutes, until 23/04/02 19:25, because of: AuthenticationError. Exception info: 'Login failed: Unauthorized'`

I just merged my account from OpenSubtitle.org and set up a new password, added the new provider with my details (i tried both username and email - deleted the provider in between testing to be sure) and still having the same issue. 

When I merged to .com and added the new provider, I selected one of the more popular movie to search a subtitle with and still having the error.

What's also weird is that although all my other 4 providers that I have all have the status "Good", yet they don't even search for any subtitles.

**Comment by rumplin** [comment]
Same here. Please someone take a look at this.

**Comment by pchang388** [comment]
> I am also getting the same issue but for opensubtitlescom:
> 
> `Throttling opensubtitlescom for 10 minutes, until 23/04/02 19:25, because of: AuthenticationError. Exception info: 'Login failed: Unauthorized'`
> 
> I just merged my account from OpenSubtitle.org and set up a new password, added the new provider with my details (i tried both username and email - deleted the provider in between testing to be sure) and still having the same issue.
> 
> When I merged to .com and added the new provider, I selected one of the more popular movie to search a subtitle with and still having the error.
> 
> What's also weird is that although all my other 4 providers that I have all have the status "Good", yet they don't even search for any subtitles.

I didn't do the merge but seeing the same behavior using opensubtitles.com account

**Comment by rumplin** [comment]
So titlovi is useless at the moment for me:
`Throttling titlovi for 10 minutes, until 23/09/11 12:43, because of: AuthenticationError. Exception info: 'Login failed'`

I can login without issues using my web browser.

**Comment by rumplin** [comment]
I'm attaching my DEBUG log.

Please note log was redacted, because it has plain text username and password in the https://kodi.titlovi.com:443 request, these were replaced with "###REMOVED###"

[bazarr.log](https://github.com/morpheus65535/bazarr/files/12575220/bazarr.log)

**Comment by rumplin** [comment]
@morpheus65535 bumping this thread.

**Comment by rumplin** [comment]
Is there anything else we can help with? More logs? more screenshots?

**Comment by morpheus65535** [comment]
> Is there anything else we can help with? More logs? more screenshots? Does the provider for titlovi consider that the page is hosted by Cloudflare?

Free up my schedule? ;-)

Seriously I must discuss with the provider's admins because they've implemented hourly limit for database access. Bazarr doesn't keep count of how many queries have been done to providers so it's not something we can deal with. I must think about this but I'm not sure we'll be able to do miracle here.

**Comment by morpheus65535** [comment]
@rumplin next beta will include a fix that should prevent this issue. Can you test and confirm please?

**Comment by rumplin** [comment]
Sure.

**Comment by rumplin** [comment]
So here is the log:

```
2024-01-14 13:45:19|INFO    |subliminal_patch.core           |Listing subtitles with provider 'titlovi' and languages {<Language: alpha3=slv>}|
2024-01-14 13:45:19|INFO    |subliminal_patch.core           |Initializing provider titlovi|
2024-01-14 13:45:19|DEBUG   |subliminal_patch.providers.titlovi|Token not found in cache|
2024-01-14 13:45:19|DEBUG   |urllib3.connectionpool          |Starting new HTTPS connection (1): kodi.titlovi.com:443|
2024-01-14 13:45:19|DEBUG   |urllib3.connectionpool          |https://kodi.titlovi.com:443 "POST /api/subtitles/gettoken?username=###REMOVED###&password=###REMOVED###&json=True HTTP/1.1" 401 0|
2024-01-14 13:45:19|ERROR   |subliminal_patch.core           |Unexpected error in provider 'titlovi': Traceback (most recent call last):  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/core.py", line 366, in list_subtitles_provider    results = self[provider].list_subtitles(video, to_request)              ~~~~^^^^^^^^^^  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/core.py", line 296, in __getitem__    provider.initialize()  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/titlovi.py", line 166, in initialize    self.log_in()  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/titlovi.py", line 182, in log_in    raise AuthenticationError('Login failed')subliminal.exceptions.AuthenticationError: Login failed|Traceback (most recent call last):  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/core.py", line 366, in list_subtitles_provider    results = self[provider].list_subtitles(video, to_request)              ~~~~^^^^^^^^^^  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/core.py", line 296, in __getitem__    provider.initialize()  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/titlovi.py", line 166, in initialize    self.log_in()  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/titlovi.py", line 182, in log_in    raise AuthenticationError('Login failed')subliminal.exceptions.AuthenticationError: Login failed|
2024-01-14 13:45:19|INFO    |root                            |Throttling titlovi for 12 hours, until 24/01/15 01:45, because of: AuthenticationError. Exception info: "'Login failed' ~ titlovi.py@182"|
2024-01-14 13:45:19|INFO    |socketio.server                 |emitting event "data" to all [/]|
2024-01-14 13:45:19|INFO    |engineio.server                 |7YyXSMYwLXNVuHTcAAAE: Sending packet MESSAGE data 2["data",{"type":"badges","action":"update","payload":null}]|
```

**Comment by morpheus65535** [comment]
> So here is the log:
> 
> ```
> 2024-01-14 13:45:19|INFO    |subliminal_patch.core           |Listing subtitles with provider 'titlovi' and languages {<Language: alpha3=slv>}|
> 2024-01-14 13:45:19|INFO    |subliminal_patch.core           |Initializing provider titlovi|
> 2024-01-14 13:45:19|DEBUG   |subliminal_patch.providers.titlovi|Token not found in cache|
> 2024-01-14 13:45:19|DEBUG   |urllib3.connectionpool          |Starting new HTTPS connection (1): kodi.titlovi.com:443|
> 2024-01-14 13:45:19|DEBUG   |urllib3.connectionpool          |https://kodi.titlovi.com:443 "POST /api/subtitles/gettoken?username=###REMOVED###&password=###REMOVED###&json=True HTTP/1.1" 401 0|
> 2024-01-14 13:45:19|ERROR   |subliminal_patch.core           |Unexpected error in provider 'titlovi': Traceback (most recent call last):  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/core.py", line 366, in list_subtitles_provider    results = self[provider].list_subtitles(video, to_request)              ~~~~^^^^^^^^^^  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/core.py", line 296, in __getitem__    provider.initialize()  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/titlovi.py", line 166, in initialize    self.log_in()  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/titlovi.py", line 182, in log_in    raise AuthenticationError('Login failed')subliminal.exceptions.AuthenticationError: Login failed|Traceback (most recent call last):  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/core.py", line 366, in list_subtitles_provider    results = self[provider].list_subtitles(video, to_request)              ~~~~^^^^^^^^^^  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/core.py", line 296, in __getitem__    provider.initialize()  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/titlovi.py", line 166, in initialize    self.log_in()  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/titlovi.py", line 182, in log_in    raise AuthenticationError('Login failed')subliminal.exceptions.AuthenticationError: Login failed|
> 2024-01-14 13:45:19|INFO    |root                            |Throttling titlovi for 12 hours, until 24/01/15 01:45, because of: AuthenticationError. Exception info: "'Login failed' ~ titlovi.py@182"|
> 2024-01-14 13:45:19|INFO    |socketio.server                 |emitting event "data" to all [/]|
> 2024-01-14 13:45:19|INFO    |engineio.server                 |7YyXSMYwLXNVuHTcAAAE: Sending packet MESSAGE data 2["data",{"type":"badges","action":"update","payload":null}]|
> ```

Your account is locked on the provider, you must make them unlock it first and it shouldn't get locked anymore after that.

**Comment by JackTorrance1** [comment]
> OK, let's stop all activity with this. Just found out that the site is closing on the 1st February 2024. R.I.P. titlovi.

No, the site is not closing down. Maybe there will be a new owner of the site, but the site will work as usual.

**Comment by rumplin** [comment]
> > OK, let's stop all activity with this. Just found out that the site is closing on the 1st February 2024. R.I.P. titlovi.
> 
> No, the site is not closing down. Maybe there will be a new owner of the site, but the site will work as usual.

They are looking for someone to take over the site: https://titlovi.com/clanci/8833/gasenje-sajta-ni-slucajno/

**Comment by dusanzk** [comment]
> > > OK, let's stop all activity with this. Just found out that the site is closing on the 1st February 2024. R.I.P. titlovi.
> > 
> > 
> > No, the site is not closing down. Maybe there will be a new owner of the site, but the site will work as usual.
> 
> They are looking for someone to take over the site: https://titlovi.com/clanci/8833/gasenje-sajta-ni-slucajno/

It is confusing as to exactly what is going on.

While the picture does say "Sorry but we're not closing" and the title reads Gašenje sajta ? Ni slučajno (Shutting the site down ? No way).

The actual text written by Nikola reads otherwise. He states that the planned date for shutting down the site is 01.02.2024 and that someone else taking over the site is a possibility, he doesn't say it's going to happen, only that he sees that as a possible solution.

**Comment by rumplin** [comment]
using a new account on titlovi, with v1.4.1-beta.16, seems to be fine now.

**Comment by rumplin** [comment]
> > using a new account on titlovi, with v1.4.1-beta.16, seems to be fine now.
> 
> I'll leave this open for a while until we can confirm account doesn't get locked anymore and what happen with this provider.

The initial bug is fixed.

Provider has news posted that the site will continue to exist.
https://titlovi.com/clanci/8875/ostajemo-online/

**Comment by morpheus65535** [comment]
> The initial bug is fixed.

I close this issue then. Thanks for testing!

**Comment by pentago** [comment]
I still have the issue with this provider.
I updated bazarr to latest and also just create a new account, the issue remains.

```
Throttling titlovi for 12 hours, until 24/02/17 05:09, because of: AuthenticationError. Exception info: "'Login failed' ~ titlovi.py@182"
```

I made sure I entered correct creds.

Some build data:
v1.4.1-ls238 image by linuxserver.io
![](https://i.imgur.com/U7We2Rf.png)

Any more ideas?

**Comment by rumplin** [comment]
@pentago try creating a new user on the site. It worked for me.

**Comment by pentago** [comment]
I said in comment above that I just did that too :) didn't help.
