### ISSUE TITLE
Repeated downloads for the same movie

### ISSUE THREAD

**Issue by clowg** [morpheus65535/bazarr#2189]
**Describe the bug**
Bazarr keeps downloading subtitles for 'Sherlock Holmes A Game of Shadows' over & over & over.
Also, the movie page in Bazarr shows as there being no subs available. A manual [Scan Disk] finds nothing. But the .en.srt file is there.

I have tried renaming the movie file to ensure there are no special characters.
I tried deleting the srt file and then manually uploading a copy. [Scan Disk] still didn't recognise the file, and Bazarr then re-downloaded it again a few hours later.

**To Reproduce**
No steps required - it is happening automatically 

**Expected behavior**
Download once, and then never again.

**Software (please complete the following information):**
-  Bazarr: 1.2.2
-  Radarr version: 4.6.3.7516
-  Sonarr version: 3.0.10.1567
-  OS: Windows 10

Debug log from last few hours:
[bazarr.log](https://github.com/morpheus65535/bazarr/files/11923858/bazarr.log)

**Comment by morpheus65535** [comment]
If I'm read your ~28700 lines long log file correctly you have enabled subtitles synchronization debug logging without reading the warning that came with it. Am I wrong?

**Comment by clowg** [comment]
No, I saw the warning. "Debug logging should only be enabled temporarily"
I thought the debug log would give the info required to troubleshoot the issue? Isn't that what logs are for?

**Comment by morpheus65535** [comment]
Not this one, the one in Settings-->Subtitles:

![image](https://github.com/morpheus65535/bazarr/assets/5130500/0b6edaaa-d2c2-453c-9587-001eadef46c8)

**Comment by clowg** [comment]
No, I didn't turn that one on:
***@***.***

**Comment by morpheus65535** [comment]
Can you provide the subtitles file please? Bazarr doesn't seems to be able to guess the file encoding.

**Comment by clowg** [comment]
[Sherlock Holmes A Game of Shadows.en.srt.txt](https://github.com/morpheus65535/bazarr/files/11962384/Sherlock.Holmes.A.Game.of.Shadows.en.srt.txt)
Here is the file. Just added .txt to filename to allow uploading.
Bazarr has been downloading the sub file from various sources. As part of the troubleshooting I added a couple of the sources to the Block list.

**Comment by morpheus65535** [comment]
I've just saved the file alongside a movie than give it a proper name (movie.en.srt) and it's been properly indexed and removed from wanted. Does yours get removed from wanted before getting downloaded over and over again?

**Comment by clowg** [comment]
No, its still in the Wanted list.

**Comment by morpheus65535** [comment]
Should be fixed in upcoming beta. Can you confirm?

**Comment by clowg** [comment]
I changed to the Development track.
Did a Update Bazarr.
Now running 1.2.3-Beta.3.
Movie shows as subtitles missing.
Did a [Scan Disk] - still shows as missing.
Did a manual search. Subtitles were downloaded again, but still shows as missing.

So you want me to re-enable logging?

**Comment by morpheus65535** [comment]
Please provide a new debug log while doing a scan disk for the movie.

**Comment by clowg** [comment]
[bazarr.log.txt](https://github.com/morpheus65535/bazarr/files/12008823/bazarr.log.txt)

Here is the requested Debug log file.

**Comment by morpheus65535** [comment]
`11/07/2023 10:04:11|DEBUG   |root                            |BAZARR storing those languages to DB: [['en', '\\\\Media2\\Movies\\Sherlock Holmes A Game of Shadows (2011)\\Sherlock Holmes A Game of Shadows.en.srt', 100544]]|`

The subtitles seems to be indexed properly? Do you see it in the UI? Is it still in the wanted list?

**Comment by clowg** [comment]
Yes, it is showing up on the Movie page in Bazarr, and it has gone from the Wanted list.

**Comment by morpheus65535** [comment]
So, now it shouldn't download in loop anymore, right?

**Comment by clowg** [comment]
Correct. It is not looping anymore.
Thanks for your help.

**Comment by clowg** [comment]
This same repeated download issue is happening again.
This time it is on 4 newly added episodes of a TV show. The same four keep downloading every few hours.
These four episodes all have yellow [EN] language icons, where as all the other episodes in that series have purple icons.
They do still appear in the Wanted list.

Currently running 1.2.4-beta.0
Shall I enable Debug logs again?

i just did a manual search for the 4 Ep's from the Wanted/Episodes screen and then the Ep's have been removed from that Wanted list. Let's see if they stay off it.

**Comment by morpheus65535** [comment]
You mean that you run a `Scan disk` for the series and the subtitles got index properly?

**Comment by clowg** [comment]
No, I went on to the Wanted\Episodes page and clicked the purple search EN button on the far right on each of the 4 episodes and new downloads happened for each one. Then when I refreshed that page the 4 episodes disappeared form the list.
