### ISSUE TITLE
modify opensubtitles api key 

### ISSUE THREAD

**Issue by tldm-gh** [morpheus65535/bazarr#2206]
I think the static api_key causing issues with authentication- can you modify below so api_key also references the config.ini file like the username and password?
This way people can use their own api_key to avoid issues.

https://github.com/morpheus65535/bazarr/blob/3c2f9404690b6bcac300fb1204180beba7d7dad2/bazarr/app/get_providers.py#L227-L231

**Comment by morpheus65535** [comment]
Even if I appreciate the time you've taken to look at this, I can confirm that this is not the issue here. I'm working with os.com admins multiple times a week to help them fix issues on their side and improve how we use their API from our side. This authentication issue is an ongoing work and using a shared api-key is the proper way to use the os.com API.

**Comment by tldm-gh** [comment]
No worries, I was having issues today, and went investigating.
Changing the api key fixed the issue for me.

Anyway appreciate your help.

**Comment by morpheus65535** [comment]
What was your exact issue? Any log?

**Comment by tldm-gh** [comment]
Nothing was downloading.
Sorry I've cleared the logs, but the logs were returning something about an invalid token after they attempted to authenticate. 

I'll see I saved anything anywhere.

**Comment by morpheus65535** [comment]
Clearing logs from Bazarr UI is only a log rotation. You can find the old logs in `config/log`.

**Comment by tldm-gh** [comment]
I'll have a look.

I did notice that the logs were showing the OS password in plain text (for the error message), might be worth fixing.

**Comment by tldm-gh** [comment]
Here you go,  

Removed the repose header a is it long

`22/07/2023 13:42:28|DEBUG   |root                            |opensubtitlescom returned a non standard response. Logging request/response for debugging purpose.|
22/07/2023 13:42:28|DEBUG   |root                            |Request URL: https://api.opensubtitles.com/api/v1/download|
22/07/2023 13:42:28|DEBUG   |root                            |Request Headers: {'User-Agent': 'Bazarr/1.2.3', 'Api-Key': 's38zmzVlW7IlYruWi7mHwDYl2SfMQoC1', 'Content-Type': 'application/json', 'Accept': 'application/json', 'Authorization': 'Bearer [TOKEN REDACTED]', 'Content-Length': '41'}|
22/07/2023 13:42:28|DEBUG   |root                            |Request Body: b'{"file_id": 3109020, "sub_format": "srt"}'|
22/07/2023 13:42:28|DEBUG   |root                            |Response Status Code: 401|
22/07/2023 13:42:28|DEBUG   |root                            |Response Headers: {[REMOVED]}|
22/07/2023 13:42:28|DEBUG   |root                            |Response Body: {"message":"invalid token","uk":"app_166_123.123.123.123","uid":2,"ts":1689997347}|
22/07/2023 13:42:28|DEBUG   |root                            |Authentication failed: clearing cache and attempting to login.|`

**Comment by morpheus65535** [comment]
I'm releasing v1.2.4 that should help fix that issue.

**Comment by Bryan792** [comment]
On 1.2.4, getting the same invalid token issue

**Comment by morpheus65535** [comment]
@Bryan792 If it doesn't work with 1.2.4, I suggest you open an issue on their forum. Could be related to your account.

**Comment by tldm-gh** [comment]
The issue still persist for me too, however it seems to be intermittent. For the last few days the I get the invalid token response  until about 10:00 UTC, then it Bazarr starts to work again without issue.  

`{"message":"invalid token","uk":"app_58245_[IP-address]","uid":2,"ts":1690191972}`

**Comment by morpheus65535** [comment]
They had a token caching issue that they have fixed this morning. Should be working now.

**Comment by tldm-gh** [comment]
Makes sense, but I don't think it's resolved. I'm still getting the error.

**Comment by morpheus65535** [comment]
Keep feeding this forum post: https://forum.opensubtitles.org/viewtopic.php?f=11&t=18292

**Comment by tldm-gh** [comment]
> Keep feeding this forum post: https://forum.opensubtitles.org/viewtopic.php?f=11&t=18292
Thanks, will do.
