### ISSUE TITLE
Embedded Subtitles transform ass to srt

### ISSUE THREAD

**Issue by MiguelAngelLV** [morpheus65535/bazarr#2514]
**Describe the bug**
When Bazarr extracts an ass subtitle from mkv, the file is converted to  .srt (not only the extension, complete conversion).

I have selected "use original format" and the problem persists.
 

**To Reproduce**
1. Enable Embedded Provider
2. Enable "User original format"
3. "Download" an ass subtitle from a mkv

**Expected behavior**
Get an .ass subtitle

**Screenshots**

![image](https://github.com/morpheus65535/bazarr/assets/638110/dc289cc5-585a-4837-90d4-661f168208e1)

![image](https://github.com/morpheus65535/bazarr/assets/638110/1205d1f2-9ec3-4a89-a7e3-10b7df55642c)

![image](https://github.com/morpheus65535/bazarr/assets/638110/0dce3ead-aa3b-4b2a-b400-d3a60af40f8a)

![image](https://github.com/morpheus65535/bazarr/assets/638110/ae31335b-e3f5-40df-9072-8df30d9d96e7)

**Software (please complete the following information):**
 - Bazarr: 1.4.3
 - Radarr version: 5.6.0.8846
 - Sonarr version 4.0.5.1710
 - OS: Linux (Raspberry Pi)

**Additional context**

**Comment by hnorgaar** [comment]
Both your Sonarr and Radarr version is years old, so please update

**Comment by MiguelAngelLV** [comment]
Updated the Sonarr and Radarr version in the issue description, although I actually use bazarr manually normally.

**Comment by MiguelAngelLV** [comment]
I don't have any post process:

![image](https://github.com/morpheus65535/bazarr/assets/638110/97fda9f0-1838-4884-9b7b-aa8041dd0b67)

**Comment by morpheus65535** [comment]
@vitiko98 Could you take a moment to check this one please?

**Comment by vitiko98** [comment]
I will need some debug logs from your part. This is probably caused by a fallback command from ffmpeg's adapter.

This is a test over a normal container with ASS subtitles, and the Subtitle interface is getting the respective format:

![image](https://github.com/morpheus65535/bazarr/assets/59455966/44520169-4c80-41ba-b37e-bf851104dee8)

**Comment by MiguelAngelLV** [comment]
```bash
2024-06-18 10:39:59|INFO    |subliminal_patch.core_persistent|Downloading subtitle <EmbeddedSubtitle: [Erai-raws] Henjin no Salad Bowl - 11 [1080p][Multiple Subtitle][FDD51DB0].es.ass [<Language: alpha3=spa>]> with score 360|
2024-06-18 10:39:59|INFO    |subliminal_patch.core           |Downloading subtitle <EmbeddedSubtitle: [Erai-raws] Henjin no Salad Bowl - 11 [1080p][Multiple Subtitle][FDD51DB0].es.ass [<Language: alpha3=spa>]>|
2024-06-18 10:39:59|DEBUG   |fese.tags                       |Detected tags class: <class 'fese.tags.FFprobeMkvSubtitleTags'>|
2024-06-18 10:39:59|DEBUG   |fese.disposition                |Generic disposition title found: english|
2024-06-18 10:39:59|DEBUG   |fese.tags                       |Detected tags class: <class 'fese.tags.FFprobeMkvSubtitleTags'>|
2024-06-18 10:39:59|DEBUG   |fese.tags                       |Found extra language ('por', 'BR')|
2024-06-18 10:39:59|DEBUG   |fese.disposition                |Generic disposition title found: portuguese(brazil)|
2024-06-18 10:39:59|DEBUG   |fese.tags                       |Detected tags class: <class 'fese.tags.FFprobeMkvSubtitleTags'>|
2024-06-18 10:39:59|DEBUG   |fese.tags                       |Found extra language ('spa', 'MX')|
2024-06-18 10:39:59|DEBUG   |fese.disposition                |Generic disposition title found: spanish(latin_america)|
2024-06-18 10:39:59|DEBUG   |fese.tags                       |Detected tags class: <class 'fese.tags.FFprobeMkvSubtitleTags'>|
2024-06-18 10:39:59|DEBUG   |fese.disposition                |Generic disposition title found: spanish|
2024-06-18 10:39:59|DEBUG   |fese.tags                       |Detected tags class: <class 'fese.tags.FFprobeMkvSubtitleTags'>|
2024-06-18 10:39:59|DEBUG   |fese.disposition                |Generic disposition title found: french|
2024-06-18 10:39:59|DEBUG   |fese.tags                       |Detected tags class: <class 'fese.tags.FFprobeMkvSubtitleTags'>|
2024-06-18 10:39:59|DEBUG   |fese.disposition                |Generic disposition title found: german|
2024-06-18 10:39:59|DEBUG   |fese.tags                       |Detected tags class: <class 'fese.tags.FFprobeMkvSubtitleTags'>|
2024-06-18 10:39:59|DEBUG   |fese.disposition                |Generic disposition title found: italian|
2024-06-18 10:39:59|DEBUG   |fese.tags                       |Detected tags class: <class 'fese.tags.FFprobeMkvSubtitleTags'>|
2024-06-18 10:39:59|DEBUG   |fese.disposition                |Generic disposition title found: russian|
2024-06-18 10:39:59|DEBUG   |fese.container                  |Found subtitle streams: [<ASS: FFprobeMkvSubtitleTags: en@GENERIC>, <ASS: FFprobeMkvSubtitleTags: pt-BR@GENERIC>, <ASS: FFprobeMkvSubtitleTags: es-MX@GENERIC>, <ASS: FFprobeMkvSubtitleTags: es@GENERIC>, <ASS: FFprobeMkvSubtitleTags: fr@GENERIC>, <ASS: FFprobeMkvSubtitleTags: de@GENERIC>, <ASS: FFprobeMkvSubtitleTags: it@GENERIC>, <ASS: FFprobeMkvSubtitleTags: ru@GENERIC>]|
2024-06-18 10:39:59|DEBUG   |fese.container                  |Appending subtitle path: /config/cache/embeddedsubtitlesprovider/4d07dab166da43448aa66343ccd229f5.ass|
2024-06-18 10:39:59|DEBUG   |fese.container                  |Appending subtitle path: /config/cache/embeddedsubtitlesprovider/84ff934bead9080ba7793804e5110321.ass|
2024-06-18 10:39:59|DEBUG   |fese.container                  |Appending subtitle path: /config/cache/embeddedsubtitlesprovider/e449c34ceb522658ed17b041ae61c6cb.ass|
2024-06-18 10:39:59|DEBUG   |fese.container                  |Appending subtitle path: /config/cache/embeddedsubtitlesprovider/df6b08f1429fb87ca322af06acdef581.ass|
2024-06-18 10:39:59|DEBUG   |fese.container                  |Appending subtitle path: /config/cache/embeddedsubtitlesprovider/0e2edc5a7104f0cb9d9c89ca04e37084.ass|
2024-06-18 10:39:59|DEBUG   |fese.container                  |Appending subtitle path: /config/cache/embeddedsubtitlesprovider/c5786fda36789823f1ec054bbaf495e0.ass|
2024-06-18 10:39:59|DEBUG   |fese.container                  |Appending subtitle path: /config/cache/embeddedsubtitlesprovider/223c97ac1fe8e87187de7c3eaa2f730c.ass|
2024-06-18 10:39:59|DEBUG   |fese.container                  |Appending subtitle path: /config/cache/embeddedsubtitlesprovider/46f35750b3569d7addda6e9a550804a7.ass|
2024-06-18 10:39:59|DEBUG   |fese.container                  |Extracting subtitle with command /usr/bin/ffmpeg -v warning -y -i /media/shows/A Salad Bowl of Eccentrics/[Erai-raws] Henjin no Salad Bowl - 11 [1080p][Multiple Subtitle][FDD51DB0].mkv -map 0:2 -c:s copy -f ass /config/cache/embeddedsubtitlesprovider/4d07dab166da43448aa66343ccd229f5.ass -map 0:3 -c:s copy -f ass /config/cache/embeddedsubtitlesprovider/84ff934bead9080ba7793804e5110321.ass -map 0:4 -c:s copy -f ass /config/cache/embeddedsubtitlesprovider/e449c34ceb522658ed17b041ae61c6cb.ass -map 0:5 -c:s copy -f ass /config/cache/embeddedsubtitlesprovider/df6b08f1429fb87ca322af06acdef581.ass -map 0:6 -c:s copy -f ass /config/cache/embeddedsubtitlesprovider/0e2edc5a7104f0cb9d9c89ca04e37084.ass -map 0:7 -c:s copy -f ass /config/cache/embeddedsubtitlesprovider/c5786fda36789823f1ec054bbaf495e0.ass -map 0:8 -c:s copy -f ass /config/cache/embeddedsubtitlesprovider/223c97ac1fe8e87187de7c3eaa2f730c.ass -map 0:9 -c:s copy -f ass /config/cache/embeddedsubtitlesprovider/46f35750b3569d7addda6e9a550804a7.ass|
2024-06-18 10:40:03|INFO    |engineio.server                 |L4UyzmmD6tjQIUmwAAAA: Client is gone, closing socket|
2024-06-18 10:40:03|INFO    |engineio.server                 |L4UyzmmD6tjQIUmwAAAA: Client is gone, closing socket|
2024-06-18 10:40:19|INFO    |engineio.server                 |mRCzOlrX1s0ux2leAAAC: Sending packet PING data None|
2024-06-18 10:40:19|INFO    |engineio.server                 |mRCzOlrX1s0ux2leAAAC: Received packet PONG data |
2024-06-18 10:40:30|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): ***.***.***.***:7878|
2024-06-18 10:40:30|DEBUG   |urllib3.connectionpool          |http://***.***.***.***:7878 "GET /api/system/status?apikey=(removed) HTTP/1.1" 404 0|
2024-06-18 10:40:30|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): ***.***.***.***:7878|
2024-06-18 10:40:30|DEBUG   |urllib3.connectionpool          |http://***.***.***.***:7878 "GET /api/v3/system/status?apikey=(removed) HTTP/1.1" 200 None|
2024-06-18 10:40:30|DEBUG   |root                            |BAZARR got this Radarr version from its API: 5.6.0.8846|
2024-06-18 10:40:39|DEBUG   |subliminal_patch.providers.embeddedsubtitles|Found modifiers for <ASS: FFprobeMkvSubtitleTags: es@GENERIC> type: {<function _clean_ass_subtitles at 0x7f7da562a0>}|
2024-06-18 10:40:39|DEBUG   |subliminal_patch.providers.embeddedsubtitles|Running <function _clean_ass_subtitles at 0x7f7da562a0> modifier for /config/cache/embeddedsubtitlesprovider/df6b08f1429fb87ca322af06acdef581.ass|
2024-06-18 10:40:39|DEBUG   |subliminal_patch.providers.embeddedsubtitles|Cleaned lines: 33|
2024-06-18 10:40:39|DEBUG   |subliminal_patch.providers.embeddedsubtitles|Lines written to output path: /config/cache/embeddedsubtitlesprovider/df6b08f1429fb87ca322af06acdef581.ass|
2024-06-18 10:40:39|INFO    |subliminal_patch.subtitle       |Guessing encoding for language es|
2024-06-18 10:40:39|DEBUG   |subliminal_patch.subtitle       |Trying encodings ['utf-8', 'windows-1252', 'iso-8859-15', 'iso-8859-9', 'iso-8859-4', 'iso-8859-1']|
2024-06-18 10:40:39|INFO    |subliminal_patch.subtitle       |Guessed encoding utf-8|
2024-06-18 10:40:39|ERROR   |subliminal_patch.subtitle       |PySRT-parsing failed, trying pysubs2|
2024-06-18 10:40:39|DEBUG   |subliminal_patch.subtitle       |Trying parsing with PySubs2|
2024-06-18 10:40:39|DEBUG   |root                            |at line 1: section heading [Script Info]|
2024-06-18 10:40:39|DEBUG   |root                            |at line 12: section heading [V4+ Styles]|
2024-06-18 10:40:39|DEBUG   |root                            |at line 28: section heading [Events]|
2024-06-18 10:40:39|INFO    |subliminal_patch.subtitle       |Got format: ass|
2024-06-18 10:40:39|DEBUG   |root                            |BAZARR Subtitles file downloaded for this file: /media/shows/A Salad Bowl of Eccentrics/[Erai-raws] Henjin no Salad Bowl - 11 [1080p][Multiple Subtitle][FDD51DB0].mkv|
2024-06-18 10:40:39|DEBUG   |subliminal_patch.core           |Subtitle formats requested: ('srt',)|
2024-06-18 10:40:39|DEBUG   |subliminal_patch.core           |Saving <EmbeddedSubtitle: [Erai-raws] Henjin no Salad Bowl - 11 [1080p][Multiple Subtitle][FDD51DB0].es.ass [<Language: alpha3=spa>]> to '/media/shows/A Salad Bowl of Eccentrics/[Erai-raws] Henjin no Salad Bowl - 11 [1080p][Multiple Subtitle][FDD51DB0].es.srt'|
2024-06-18 10:40:39|DEBUG   |root                            |BAZARR Subtitles file saved to disk: /media/shows/A Salad Bowl of Eccentrics/[Erai-raws] Henjin no Salad Bowl - 11 [1080p][Multiple Subtitle][FDD51DB0].es.srt|
2024-06-18 10:40:39|DEBUG   |root                            |Sync checker: <function sync_checker at 0x7f82342660>|
2024-06-18 10:40:39|DEBUG   |root                            |Checker data [{'blacklisted_languages': [], 'blacklisted_providers': ['embeddedsubtitles', 'subtitulamostv']}] for <EmbeddedSubtitle: [Erai-raws] Henjin no Salad Bowl - 11 [1080p][Multiple Subtitle][FDD51DB0].es.ass [<Language: alpha3=spa>]>|
2024-06-18 10:40:39|DEBUG   |root                            |BAZARR Sync checker not passed. Won't sync.|
2024-06-18 10:40:39|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): ***.***.***.***:8989|
2024-06-18 10:40:39|DEBUG   |urllib3.connectionpool          |http://***.***.***.***:8989 "POST /api/v3/command?apikey=(removed) HTTP/1.1" 201 None|
2024-06-18 10:40:39|INFO    |socketio.server                 |emitting event "data" to all [/]|
2024-06-18 10:40:39|INFO    |engineio.server                 |mRCzOlrX1s0ux2leAAAC: Sending packet MESSAGE data 2["data",{"type":"series","action":"update","payload":50}]|
2024-06-18 10:40:39|INFO    |socketio.server                 |emitting event "data" to all [/]|
2024-06-18 10:40:39|INFO    |engineio.server                 |mRCzOlrX1s0ux2leAAAC: Sending packet MESSAGE data 2["data",{"type":"episode-wanted","action":"delete","payload":4055}]|
2024-06-18 10:40:39|INFO    |socketio.server                 |emitting event "data" to all [/]|
2024-06-18 10:40:39|INFO    |engineio.server                 |mRCzOlrX1s0ux2leAAAC: Sending packet MESSAGE data 2["data",{"type":"episode-history","action":"update","payload":null}]|
2024-06-18 10:40:39|DEBUG   |apprise                         |Language set to en|
```

**Comment by MiguelAngelLV** [comment]
The problem may be this:

```
2024-06-18 10:40:39|DEBUG   |subliminal_patch.core           |Subtitle formats requested: ('srt',)|
```
But I have checked "use original format".

Maybe there are another option for request format?

**Comment by vitiko98** [comment]
Logs did the trick. I think this is related to an attribute from `Subtitle`.

Please try again in upcoming beta.

**Comment by MiguelAngelLV** [comment]
I tried beta 10, the problem persists:


```
2024-06-24 15:51:35|DEBUG   |subliminal_patch.subtitle       |Trying parsing with PySubs2|
2024-06-24 15:51:35|DEBUG   |root                            |at line 1: section heading [Script Info]|
2024-06-24 15:51:35|DEBUG   |root                            |at line 12: section heading [V4+ Styles]|
2024-06-24 15:51:35|DEBUG   |root                            |at line 27: section heading [Events]|
2024-06-24 15:51:35|INFO    |subliminal_patch.subtitle       |Got format: ass|
2024-06-24 15:51:35|DEBUG   |root                            |BAZARR Subtitles file downloaded for this file: /media/shows/Mushoku Tensei - Jobless Reincarnation/Season 2/[Judas] Mushoku Tensei - S02E23.mkv|
2024-06-24 15:51:35|DEBUG   |subliminal_patch.subtitle       |Will assume srt format|
2024-06-24 15:51:35|DEBUG   |subliminal_patch.core           |Subtitle formats requested: ('srt',)|
2024-06-24 15:51:35|DEBUG   |subliminal_patch.core           |Saving <EmbeddedSubtitle: [Judas] Mushoku Tensei - S02E23.es.ass [<Language: alpha3=spa;hi=True>]> to '/media/shows/Mushoku Tensei - Jobless Reincarnation/Season 2/[Judas] Mushoku Tensei - S02E23.es.hi.srt'|
2024-06-24 15:51:35|DEBUG   |root                            |BAZARR Subtitles file saved to disk: /media/shows/Mushoku Tensei - Jobless Reincarnation/Season 2/[Judas] Mushoku Tensei - S02E23.es.hi.srt|
2024-06-24 15:51:35|DEBUG   |root                            |Sync checker: <function sync_checker at 0x7fb9bb6660>|
2024-06-24 15:51:35|DEBUG   |root                            |Checker data [{'blacklisted_languages': [], 'blacklisted_providers': ['embeddedsubtitles', 'subtitulamostv']}] for <EmbeddedSubtitle: [Judas] Mushoku Tensei - S02E23.es.ass [<Language: alpha3=spa;hi=True>]>|
2024-06-24 15:51:35|DEBUG   |root                            |BAZARR Sync checker not passed. Won't sync.|
2024-06-24 15:51:35|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): ***.***.***.***:8989|
2024-06-24 15:51:35|DEBUG   |urllib3.connectionpool          |http://***.***.***.***:8989 "POST /api/v3/command?apikey=(removed) HTTP/1.1" 201 None|
``

**Comment by vitiko98** [comment]
@MiguelAngelLV Manual download or automatic download?

**Comment by MiguelAngelLV** [comment]
@vitiko98  manual

**Comment by vitiko98** [comment]
So it might be related to the REST API.

This is the payload for manual episode subtitles:

![image](https://github.com/morpheus65535/bazarr/assets/59455966/1729fdee-4125-4459-b000-8913e902719d)

The code in `api/providers/provider_episodes.py` is expecting it to be a literal boolean string:

![image](https://github.com/morpheus65535/bazarr/assets/59455966/85eb4e07-7ea5-4739-bfea-4f8a887b6a68)

Consequentially, the code in `bazarr/subtitles/manual.py` will return False no matter the payload.

![image](https://github.com/morpheus65535/bazarr/assets/59455966/1ba26619-dc43-4054-b603-8d658920f5d8)

I made a commit to mitigate this. Try in upcoming beta.

**Comment by morpheus65535** [comment]
@MiguelAngelLV can you confirm if the issue is fixed?

**Comment by MiguelAngelLV** [comment]
Solved!

**Comment by LucasD-C** [comment]
This is working only when using manual search. When doing automatic search it still gives you an srt sub.

**Comment by irfanhakim-as** [comment]
May I know if this issue is expected, currently, to only work/be fixed with manual search and still _broken_ with auto? I'm on a very recent version of Bazarr/Radarr/Sonarr and I'm also noticing that `ass` subs are being extracted as `srt`. ~~Video players like MPV possibly still recognises it as an `ass` file though, but the file extension is definitely `srt`.~~

edit: that last sentence, I got it wrong. MPV indeed sees it as an SRT file, so it must indeed be extracted as `srt` rather than `ass` (i.e. as intended, as the original format).

**Comment by miguelangellv** [comment]
I still have problems so I created a ffmpeg script to extract the subtitles...

**Comment by irfanhakim-as** [comment]
> I still have problems so I created a ffmpeg script to extract the subtitles...

I assume this problem you have is with auto (which is - most use cases), and that it works in manual (as before)? Or has it possibly regressed?

**Comment by miguelangellv** [comment]
Yes, with auto. So now I have a HA automation that receive a sonarr notification and execute the script. More simple and I could remove bazarr.

**Comment by irfanhakim-as** [comment]
Thanks for the info. Bazarr is still very useful to me, to download missing subs, but yes this issue def needs reopening (or a new report, maybe). Would appreciate it if you could share the content of the script though if you don't mind :))

**Comment by miguelangellv** [comment]
The script find the spanish subtitles from Spain (Plex use the first "spanish" subtitle, normally, the from latam) and if it find anyone, it extract it

```bash
echo "▶ Archivo: $INPUT"
echo "▶ Carpeta temporal para logs: $TMPDIR"

# Patrones de idioma (incluir/excluir)
SPANISH_POS="(spa|^es$|es[-_]?ES|spanish|castilian|castellano)"
SPANISH_NEG="(latin|latam|es[-_]?419|es[-_]?mx|es[-_]?la|mex|argentina|chile|colombia|peru|venezuela|uruguay|forz|\bla\b)"


STREAMS=$(ffprobe -v error -select_streams s \
  -show_entries stream=index,codec_name:stream_tags=language,title \
  -of csv=p=0 "$INPUT" 2>/dev/null || true)

echo "—— ffprobe (CSV crudo) ——"
[ -n "$STREAMS" ] && echo "$STREAMS" || echo "(vacío)"
echo "———————————————"

# Ejemplo de línea: "0,subrip,spa,Castellano"
echo "Paso A1: candidatos con alguna pista de castellano (amplio)…"
CAND_SP=$(printf "%s\n" "$STREAMS" | grep -iE "$SPANISH_POS" || true)
[ -n "$CAND_SP" ] && echo "$CAND_SP" || echo "(ninguno)"

echo "Paso A2: excluir variantes latinas…"
CAND_ES=$(printf "%s\n" "$CAND_SP" | grep -ivE "$SPANISH_NEG" || true)
[ -n "$CAND_ES" ] && echo "$CAND_ES" || echo "(ninguno)"

echo "Paso A3: quedarnos solo con códecs de texto (subrip|ass)…"
CAND_TEXT=$(printf "%s\n" "$CAND_ES" | grep -iE ',(subrip|ass),' || true)
[ -n "$CAND_TEXT" ] && echo "$CAND_TEXT" || echo "(ninguno)"

SEL_LINE=$(printf "%s\n" "$CAND_TEXT" | head -n 1)
echo "Paso A4: línea seleccionada:"
[ -n "$SEL_LINE" ] && echo "$SEL_LINE" || echo "(ninguna)"

if [ -n "$SEL_LINE" ]; then
  # Índice absoluto y códec
  ABS_IDX=$(printf "%s\n" "$SEL_LINE" | awk -F',' '{print $1}')
  CODEC=$(printf "%s\n" "$SEL_LINE" | awk -F',' '{print $2}')
  LANG=$(printf "%s\n" "$SEL_LINE" | awk -F',' '{print $3}')
  TITLE=$(printf "%s\n" "$SEL_LINE" | awk -F',' '{print $4}')

  echo "✔ Elegido: abs_index=$ABS_IDX codec=$CODEC lang=$LANG title=$TITLE"

  SUBIDX=$(printf "%s\n" "$STREAMS" | awk -v sel="$SEL_LINE" 'BEGIN{n=0} {gsub(/\r$/,""); if($0==sel){print n; exit} n++ }')
  echo "Info: índice relativo de subtítulos (0:s:N) = $SUBIDX"

  # Extensión de salida según códec
  EXT="srt"; [ "$(printf "%s" "$CODEC" | tr '[:upper:]' '[:lower:]')" = "ass" ] && EXT="ass"
  OUTPUT="${BASENAME}.es.${EXT}"
  echo "Salida: $OUTPUT"

  # Extraer: usar el índice relativo (más robusto entre s:) y fijar códec de salida
  CS="srt"; [ "$EXT" = "ass" ] && CS="ass"
  echo "Comando: ffmpeg -y -i \"$INPUT\" -map 0:s:$SUBIDX -c:s $CS \"$OUTPUT\""
  ffmpeg -y -i "$INPUT" -map 0:s:$SUBIDX -c:s $CS "$OUTPUT"
  [ $? -eq 0 ] && { echo "🎉 Extraído: $OUTPUT"; exit 0; } || { echo "❌ Fallo en extracción con ffprobe."; }
else
  echo "⚠ No hay subtítulos ES (España) en texto detectados con ffprobe."
fi

```

**Comment by irfanhakim-as** [comment]
@morpheus65535 @vitiko98 sorry for pinging you but assuming this is still an issue for auto/scheduled searches (i.e. subs aren't being extracted as per their original format, e.g. `ass`, but rather as `srt`), should this issue be reopened? or filed new?

**Comment by morpheus65535** [comment]
@irfanhakim-as I've just tested with a movie that as an embedded ASS subtitles and had no issue download a subtitles with original format enabled in languages profile. It was saved with an .ass extension and the content was really ASS subtitles. I tried with interactive search, with the search button at the top of the movie page and also with the search missing subtitles task in System-->Tasks. All of them worked as expected. I can't reproduce your issue. We'll need screenshot and debug log to understand how it happens on your side.
