### ISSUE TITLE
Bazarr thinks i need HI Even if it’s not selected

### ISSUE THREAD

**Issue by Tibi-rvb** [morpheus65535/bazarr#2676]
**Describe the bug**
Language profile is set to normal or HI
Sub appears on manual search with HI and x, match of 100% or 99%
Match treshold is set at 95% so all good here.
Bazarr is not downloading the sub, thinking that I have only HI selected.
Restarting Bazarr through the interface or container fix the issue but issue is reappearing after approx a coupe of hours / 1 day

**Software (please complete the following information):**
 - Bazarr: 1.4.3
 - Sonarr version 4.0.9
 - OS: docker / Synology DSM
![IMG_0626](https://github.com/user-attachments/assets/572aee06-0b37-418f-bc73-cde8c9fdeb78)
![IMG_8744](https://github.com/user-attachments/assets/257b68ec-e856-44e3-aa77-526f500f74be)

**Comment by morpheus65535** [comment]
Should be already fixed in 1.4.4. Please update and confirm. Reopen if required.

**Comment by JaiZed** [comment]
@Tibi-rvb after a restart, this issue will reappear after you download your first HI subtitle.
This issue was fixed in 1.4.4, so update to that or you'll keep needing to restart Bazarr.

**Comment by Tibi-rvb** [comment]
Its fixed with the update. Sorry, container manager did not showed an update.

By the way: bazarr is incredible! Super helpful!!

**Comment by Tibi-rvb** [comment]
> Should be already fixed in 1.4.4. Please update and confirm. Reopen if required.

Hi, after some more tests, reverting … issue is still there with the HI subs.

**Comment by JaiZed** [comment]
You need to take this issue to Discord support.
We will need some debug logs to prove that you are having this problem.
