### ISSUE TITLE
Bazarr disk scanning wrong filename

### ISSUE THREAD

**Issue by mobamoba** [morpheus65535/bazarr#597]
Using .8.1 for Windows with Python 2.7.16.

When I do a manual scan for subtitles in a folder I know contains subtitles, Bazarr fails to find them. The reason, from looking at the command line output, is that Bazarr is scanning for the scene name and not the actual filename.

For example, instead of searching for "R:\Movies\War for the Planet of the Apes (2017)\War for the Planet of the Apes (2017).mkv" to check for a subtitle, Bazarr has saved the scene name - "War.For.The.Planet.Of.The.Apes.2017.2160p.UHD.BluRay.x265-EMERALD" - as both an alternate title (which it isn't) and the only title it searches for. 

If Bazarr searched for the blue title in the screenshot, it would find the subtitle, but it searches under the other, non-existent title for some reason and then errors out.

![image](https://user-images.githubusercontent.com/11135869/65765174-81c08d00-e0f5-11e9-86cf-e96e2d547125.png)

**Comment by morpheus65535** [comment]
Please provide a debug log (empty it before reproducing the issue).

**Comment by mobamoba** [comment]
Restart it cleared the issue. So does this mean that Bazarr is grabbing the scene names from Sonarr and Radarr and then not replacing those names with the actual filenames until a Bazarr restart?

**Comment by morpheus65535** [comment]
It shouldn't. Even if it use scenename, it should be saved with the video filename, not the scenename.

**Comment by mobamoba** [comment]
Okay if I spot this error again, I'll do a debug log before restarting and upload here so you can see what's going on.

**Comment by morpheus65535** [comment]
Thanks!

**Comment by mobamoba** [comment]
It did it again. Here's debug log output

`06/10/2019 00:58:28|ERROR   |root                            |BAZARR Error trying to get video information for this file: R:\Sorted\Great British Bake Off, The\Season 10\The Great British Bake Off - s10e06 - Dessert Week.mkv|'Traceback (most recent call last):\n  File "c:\\bazarr\\bazarr\\bazarr\\get_subtitle.py", line 64, in get_video\n    hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subzero\\video.py", line 58, in parse_video\n    skip_hashing=skip_hashing, hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subliminal_patch\\core.py", line 547, in scan_video\n    video.size = os.path.getsize(hash_path)\n  File "C:\\Python27\\lib\\genericpath.py", line 57, in getsize\n    return os.stat(filename).st_size\nWindowsError: [Error 3] The system cannot find the path specified: u\'R:\\\\Sorted\\\\Great British Bake Off, The\\\\Season 10\\\\The Great British Bake Off - 10x06 - Dessert Week.mkv\''|
06/10/2019 00:58:28|ERROR   |root                            |BAZARR Error trying to get video information for this file: R:\Sorted\Mr. Robot\Season 3\mr.robot.s03e08.1080p.bluray.x264-rovers.mkv|'Traceback (most recent call last):\n  File "c:\\bazarr\\bazarr\\bazarr\\get_subtitle.py", line 64, in get_video\n    hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subzero\\video.py", line 58, in parse_video\n    skip_hashing=skip_hashing, hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subliminal_patch\\core.py", line 547, in scan_video\n    video.size = os.path.getsize(hash_path)\n  File "C:\\Python27\\lib\\genericpath.py", line 57, in getsize\n    return os.stat(filename).st_size\nWindowsError: [Error 3] The system cannot find the path specified: u\'R:\\\\Sorted\\\\Mr. Robot\\\\Season 3\\\\Mr. Robot - 3x08 - eps3.7_dont-delete-me.ko.mkv\''|
06/10/2019 00:58:29|ERROR   |root                            |BAZARR Error trying to get video information for this file: R:\Sorted\Mr. Robot\Season 3\mr.robot.s03e09.1080p.bluray.x264-rovers.mkv|'Traceback (most recent call last):\n  File "c:\\bazarr\\bazarr\\bazarr\\get_subtitle.py", line 64, in get_video\n    hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subzero\\video.py", line 58, in parse_video\n    skip_hashing=skip_hashing, hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subliminal_patch\\core.py", line 547, in scan_video\n    video.size = os.path.getsize(hash_path)\n  File "C:\\Python27\\lib\\genericpath.py", line 57, in getsize\n    return os.stat(filename).st_size\nWindowsError: [Error 3] The system cannot find the path specified: u\'R:\\\\Sorted\\\\Mr. Robot\\\\Season 3\\\\Mr. Robot - 3x09 - eps3.8_stage3.torrent.mkv\''|
06/10/2019 00:58:29|ERROR   |root                            |BAZARR Error trying to get video information for this file: R:\Sorted\Mr. Robot\Season 3\mr.robot.s03e10.1080p.bluray.x264-rovers.mkv|'Traceback (most recent call last):\n  File "c:\\bazarr\\bazarr\\bazarr\\get_subtitle.py", line 64, in get_video\n    hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subzero\\video.py", line 58, in parse_video\n    skip_hashing=skip_hashing, hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subliminal_patch\\core.py", line 547, in scan_video\n    video.size = os.path.getsize(hash_path)\n  File "C:\\Python27\\lib\\genericpath.py", line 57, in getsize\n    return os.stat(filename).st_size\nWindowsError: [Error 3] The system cannot find the path specified: u\'R:\\\\Sorted\\\\Mr. Robot\\\\Season 3\\\\Mr. Robot - 3x10 - shutdown -r.mkv\''|
06/10/2019 00:58:30|ERROR   |root                            |BAZARR Error trying to get video information for this file: R:\Sorted\Interior Design Masters\Season 1\Interior.Design.Masters.S01E08.HDTV.x264-LiNKLE[eztv].mkv|'Traceback (most recent call last):\n  File "c:\\bazarr\\bazarr\\bazarr\\get_subtitle.py", line 64, in get_video\n    hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subzero\\video.py", line 58, in parse_video\n    skip_hashing=skip_hashing, hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subliminal_patch\\core.py", line 547, in scan_video\n    video.size = os.path.getsize(hash_path)\n  File "C:\\Python27\\lib\\genericpath.py", line 57, in getsize\n    return os.stat(filename).st_size\nWindowsError: [Error 3] The system cannot find the path specified: u\'R:\\\\Sorted\\\\Interior Design Masters\\\\Season 1\\\\Interior Design Masters - 1x08 - Episode 8.mkv\''|
06/10/2019 00:58:30|ERROR   |root                            |BAZARR Error trying to get video information for this file: R:\Movies\I Feel Good (2018)\I.Feel.Good.2018.FRENCH.BDRip.1080p.mkv|'Traceback (most recent call last):\n  File "c:\\bazarr\\bazarr\\bazarr\\get_subtitle.py", line 64, in get_video\n    hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subzero\\video.py", line 58, in parse_video\n    skip_hashing=skip_hashing, hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subliminal_patch\\core.py", line 547, in scan_video\n    video.size = os.path.getsize(hash_path)\n  File "C:\\Python27\\lib\\genericpath.py", line 57, in getsize\n    return os.stat(filename).st_size\nWindowsError: [Error 3] The system cannot find the path specified: u\'R:\\\\Movies\\\\I Feel Good (2018)\\\\I Feel Good (2018).mkv\''|
06/10/2019 00:58:30|INFO    |root                            |BAZARR Finished searching for missing subtitles. Check histories for more information.|
06/10/2019 03:58:28|ERROR   |root                            |BAZARR Error trying to get video information for this file: R:\Sorted\Great British Bake Off, The\Season 10\The Great British Bake Off - s10e06 - Dessert Week.mkv|'Traceback (most recent call last):\n  File "c:\\bazarr\\bazarr\\bazarr\\get_subtitle.py", line 64, in get_video\n    hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subzero\\video.py", line 58, in parse_video\n    skip_hashing=skip_hashing, hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subliminal_patch\\core.py", line 547, in scan_video\n    video.size = os.path.getsize(hash_path)\n  File "C:\\Python27\\lib\\genericpath.py", line 57, in getsize\n    return os.stat(filename).st_size\nWindowsError: [Error 3] The system cannot find the path specified: u\'R:\\\\Sorted\\\\Great British Bake Off, The\\\\Season 10\\\\The Great British Bake Off - 10x06 - Dessert Week.mkv\''|
06/10/2019 03:58:28|ERROR   |root                            |BAZARR Error trying to get video information for this file: R:\Sorted\Mr. Robot\Season 3\mr.robot.s03e08.1080p.bluray.x264-rovers.mkv|'Traceback (most recent call last):\n  File "c:\\bazarr\\bazarr\\bazarr\\get_subtitle.py", line 64, in get_video\n    hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subzero\\video.py", line 58, in parse_video\n    skip_hashing=skip_hashing, hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subliminal_patch\\core.py", line 547, in scan_video\n    video.size = os.path.getsize(hash_path)\n  File "C:\\Python27\\lib\\genericpath.py", line 57, in getsize\n    return os.stat(filename).st_size\nWindowsError: [Error 3] The system cannot find the path specified: u\'R:\\\\Sorted\\\\Mr. Robot\\\\Season 3\\\\Mr. Robot - 3x08 - eps3.7_dont-delete-me.ko.mkv\''|
06/10/2019 03:58:29|INFO    |root                            |BAZARR No new version of Bazarr available.|
06/10/2019 03:58:29|ERROR   |root                            |BAZARR Error trying to get video information for this file: R:\Sorted\Mr. Robot\Season 3\mr.robot.s03e09.1080p.bluray.x264-rovers.mkv|'Traceback (most recent call last):\n  File "c:\\bazarr\\bazarr\\bazarr\\get_subtitle.py", line 64, in get_video\n    hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subzero\\video.py", line 58, in parse_video\n    skip_hashing=skip_hashing, hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subliminal_patch\\core.py", line 547, in scan_video\n    video.size = os.path.getsize(hash_path)\n  File "C:\\Python27\\lib\\genericpath.py", line 57, in getsize\n    return os.stat(filename).st_size\nWindowsError: [Error 3] The system cannot find the path specified: u\'R:\\\\Sorted\\\\Mr. Robot\\\\Season 3\\\\Mr. Robot - 3x09 - eps3.8_stage3.torrent.mkv\''|
06/10/2019 03:58:30|ERROR   |root                            |BAZARR Error trying to get video information for this file: R:\Sorted\Mr. Robot\Season 3\mr.robot.s03e10.1080p.bluray.x264-rovers.mkv|'Traceback (most recent call last):\n  File "c:\\bazarr\\bazarr\\bazarr\\get_subtitle.py", line 64, in get_video\n    hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subzero\\video.py", line 58, in parse_video\n    skip_hashing=skip_hashing, hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subliminal_patch\\core.py", line 547, in scan_video\n    video.size = os.path.getsize(hash_path)\n  File "C:\\Python27\\lib\\genericpath.py", line 57, in getsize\n    return os.stat(filename).st_size\nWindowsError: [Error 3] The system cannot find the path specified: u\'R:\\\\Sorted\\\\Mr. Robot\\\\Season 3\\\\Mr. Robot - 3x10 - shutdown -r.mkv\''|
06/10/2019 03:58:31|ERROR   |root                            |BAZARR Error trying to get video information for this file: R:\Sorted\Interior Design Masters\Season 1\Interior.Design.Masters.S01E08.HDTV.x264-LiNKLE[eztv].mkv|'Traceback (most recent call last):\n  File "c:\\bazarr\\bazarr\\bazarr\\get_subtitle.py", line 64, in get_video\n    hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subzero\\video.py", line 58, in parse_video\n    skip_hashing=skip_hashing, hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subliminal_patch\\core.py", line 547, in scan_video\n    video.size = os.path.getsize(hash_path)\n  File "C:\\Python27\\lib\\genericpath.py", line 57, in getsize\n    return os.stat(filename).st_size\nWindowsError: [Error 3] The system cannot find the path specified: u\'R:\\\\Sorted\\\\Interior Design Masters\\\\Season 1\\\\Interior Design Masters - 1x08 - Episode 8.mkv\''|
06/10/2019 03:58:31|ERROR   |root                            |BAZARR Error trying to get video information for this file: R:\Movies\I Feel Good (2018)\I.Feel.Good.2018.FRENCH.BDRip.1080p.mkv|'Traceback (most recent call last):\n  File "c:\\bazarr\\bazarr\\bazarr\\get_subtitle.py", line 64, in get_video\n    hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subzero\\video.py", line 58, in parse_video\n    skip_hashing=skip_hashing, hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subliminal_patch\\core.py", line 547, in scan_video\n    video.size = os.path.getsize(hash_path)\n  File "C:\\Python27\\lib\\genericpath.py", line 57, in getsize\n    return os.stat(filename).st_size\nWindowsError: [Error 3] The system cannot find the path specified: u\'R:\\\\Movies\\\\I Feel Good (2018)\\\\I Feel Good (2018).mkv\''|
06/10/2019 03:58:31|INFO    |root                            |BAZARR Finished searching for missing subtitles. Check histories for more information.|
06/10/2019 04:00:00|INFO    |root                            |BAZARR All existing episode subtitles indexed from disk.|
06/10/2019 04:00:00|INFO    |root                            |BAZARR All missing episode subtitles updated in database.|
06/10/2019 05:00:00|INFO    |root                            |BAZARR All existing movie subtitles indexed from disk.|
06/10/2019 05:00:00|INFO    |root                            |BAZARR All missing movie subtitles updated in database.|
06/10/2019 06:58:28|ERROR   |root                            |BAZARR Error trying to get video information for this file: R:\Sorted\Great British Bake Off, The\Season 10\The Great British Bake Off - s10e06 - Dessert Week.mkv|'Traceback (most recent call last):\n  File "c:\\bazarr\\bazarr\\bazarr\\get_subtitle.py", line 64, in get_video\n    hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subzero\\video.py", line 58, in parse_video\n    skip_hashing=skip_hashing, hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subliminal_patch\\core.py", line 547, in scan_video\n    video.size = os.path.getsize(hash_path)\n  File "C:\\Python27\\lib\\genericpath.py", line 57, in getsize\n    return os.stat(filename).st_size\nWindowsError: [Error 3] The system cannot find the path specified: u\'R:\\\\Sorted\\\\Great British Bake Off, The\\\\Season 10\\\\The Great British Bake Off - 10x06 - Dessert Week.mkv\''|
06/10/2019 06:58:28|ERROR   |root                            |BAZARR Error trying to get video information for this file: R:\Sorted\Mr. Robot\Season 3\mr.robot.s03e08.1080p.bluray.x264-rovers.mkv|'Traceback (most recent call last):\n  File "c:\\bazarr\\bazarr\\bazarr\\get_subtitle.py", line 64, in get_video\n    hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subzero\\video.py", line 58, in parse_video\n    skip_hashing=skip_hashing, hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subliminal_patch\\core.py", line 547, in scan_video\n    video.size = os.path.getsize(hash_path)\n  File "C:\\Python27\\lib\\genericpath.py", line 57, in getsize\n    return os.stat(filename).st_size\nWindowsError: [Error 3] The system cannot find the path specified: u\'R:\\\\Sorted\\\\Mr. Robot\\\\Season 3\\\\Mr. Robot - 3x08 - eps3.7_dont-delete-me.ko.mkv\''|
06/10/2019 06:58:28|ERROR   |root                            |BAZARR Error trying to get video information for this file: R:\Sorted\Mr. Robot\Season 3\mr.robot.s03e09.1080p.bluray.x264-rovers.mkv|'Traceback (most recent call last):\n  File "c:\\bazarr\\bazarr\\bazarr\\get_subtitle.py", line 64, in get_video\n    hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subzero\\video.py", line 58, in parse_video\n    skip_hashing=skip_hashing, hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subliminal_patch\\core.py", line 547, in scan_video\n    video.size = os.path.getsize(hash_path)\n  File "C:\\Python27\\lib\\genericpath.py", line 57, in getsize\n    return os.stat(filename).st_size\nWindowsError: [Error 3] The system cannot find the path specified: u\'R:\\\\Sorted\\\\Mr. Robot\\\\Season 3\\\\Mr. Robot - 3x09 - eps3.8_stage3.torrent.mkv\''|
06/10/2019 06:58:29|ERROR   |root                            |BAZARR Error trying to get video information for this file: R:\Sorted\Mr. Robot\Season 3\mr.robot.s03e10.1080p.bluray.x264-rovers.mkv|'Traceback (most recent call last):\n  File "c:\\bazarr\\bazarr\\bazarr\\get_subtitle.py", line 64, in get_video\n    hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subzero\\video.py", line 58, in parse_video\n    skip_hashing=skip_hashing, hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subliminal_patch\\core.py", line 547, in scan_video\n    video.size = os.path.getsize(hash_path)\n  File "C:\\Python27\\lib\\genericpath.py", line 57, in getsize\n    return os.stat(filename).st_size\nWindowsError: [Error 3] The system cannot find the path specified: u\'R:\\\\Sorted\\\\Mr. Robot\\\\Season 3\\\\Mr. Robot - 3x10 - shutdown -r.mkv\''|
06/10/2019 06:58:30|ERROR   |root                            |BAZARR Error trying to get video information for this file: R:\Sorted\Interior Design Masters\Season 1\Interior.Design.Masters.S01E08.HDTV.x264-LiNKLE[eztv].mkv|'Traceback (most recent call last):\n  File "c:\\bazarr\\bazarr\\bazarr\\get_subtitle.py", line 64, in get_video\n    hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subzero\\video.py", line 58, in parse_video\n    skip_hashing=skip_hashing, hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subliminal_patch\\core.py", line 547, in scan_video\n    video.size = os.path.getsize(hash_path)\n  File "C:\\Python27\\lib\\genericpath.py", line 57, in getsize\n    return os.stat(filename).st_size\nWindowsError: [Error 3] The system cannot find the path specified: u\'R:\\\\Sorted\\\\Interior Design Masters\\\\Season 1\\\\Interior Design Masters - 1x08 - Episode 8.mkv\''|
06/10/2019 06:58:30|ERROR   |root                            |BAZARR Error trying to get video information for this file: R:\Movies\I Feel Good (2018)\I.Feel.Good.2018.FRENCH.BDRip.1080p.mkv|'Traceback (most recent call last):\n  File "c:\\bazarr\\bazarr\\bazarr\\get_subtitle.py", line 64, in get_video\n    hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subzero\\video.py", line 58, in parse_video\n    skip_hashing=skip_hashing, hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subliminal_patch\\core.py", line 547, in scan_video\n    video.size = os.path.getsize(hash_path)\n  File "C:\\Python27\\lib\\genericpath.py", line 57, in getsize\n    return os.stat(filename).st_size\nWindowsError: [Error 3] The system cannot find the path specified: u\'R:\\\\Movies\\\\I Feel Good (2018)\\\\I Feel Good (2018).mkv\''|
06/10/2019 06:58:30|INFO    |root                            |BAZARR Finished searching for missing subtitles. Check histories for more information.|
06/10/2019 09:58:28|ERROR   |root                            |BAZARR Error trying to get video information for this file: R:\Sorted\Great British Bake Off, The\Season 10\The Great British Bake Off - s10e06 - Dessert Week.mkv|'Traceback (most recent call last):\n  File "c:\\bazarr\\bazarr\\bazarr\\get_subtitle.py", line 64, in get_video\n    hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subzero\\video.py", line 58, in parse_video\n    skip_hashing=skip_hashing, hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subliminal_patch\\core.py", line 547, in scan_video\n    video.size = os.path.getsize(hash_path)\n  File "C:\\Python27\\lib\\genericpath.py", line 57, in getsize\n    return os.stat(filename).st_size\nWindowsError: [Error 3] The system cannot find the path specified: u\'R:\\\\Sorted\\\\Great British Bake Off, The\\\\Season 10\\\\The Great British Bake Off - 10x06 - Dessert Week.mkv\''|
06/10/2019 09:58:28|ERROR   |root                            |BAZARR Error trying to get video information for this file: R:\Sorted\Mr. Robot\Season 3\mr.robot.s03e08.1080p.bluray.x264-rovers.mkv|'Traceback (most recent call last):\n  File "c:\\bazarr\\bazarr\\bazarr\\get_subtitle.py", line 64, in get_video\n    hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subzero\\video.py", line 58, in parse_video\n    skip_hashing=skip_hashing, hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subliminal_patch\\core.py", line 547, in scan_video\n    video.size = os.path.getsize(hash_path)\n  File "C:\\Python27\\lib\\genericpath.py", line 57, in getsize\n    return os.stat(filename).st_size\nWindowsError: [Error 3] The system cannot find the path specified: u\'R:\\\\Sorted\\\\Mr. Robot\\\\Season 3\\\\Mr. Robot - 3x08 - eps3.7_dont-delete-me.ko.mkv\''|
06/10/2019 09:58:28|INFO    |root                            |BAZARR No new version of Bazarr available.|
06/10/2019 09:58:29|ERROR   |root                            |BAZARR Error trying to get video information for this file: R:\Sorted\Mr. Robot\Season 3\mr.robot.s03e09.1080p.bluray.x264-rovers.mkv|'Traceback (most recent call last):\n  File "c:\\bazarr\\bazarr\\bazarr\\get_subtitle.py", line 64, in get_video\n    hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subzero\\video.py", line 58, in parse_video\n    skip_hashing=skip_hashing, hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subliminal_patch\\core.py", line 547, in scan_video\n    video.size = os.path.getsize(hash_path)\n  File "C:\\Python27\\lib\\genericpath.py", line 57, in getsize\n    return os.stat(filename).st_size\nWindowsError: [Error 3] The system cannot find the path specified: u\'R:\\\\Sorted\\\\Mr. Robot\\\\Season 3\\\\Mr. Robot - 3x09 - eps3.8_stage3.torrent.mkv\''|
06/10/2019 09:58:30|ERROR   |root                            |BAZARR Error trying to get video information for this file: R:\Sorted\Mr. Robot\Season 3\mr.robot.s03e10.1080p.bluray.x264-rovers.mkv|'Traceback (most recent call last):\n  File "c:\\bazarr\\bazarr\\bazarr\\get_subtitle.py", line 64, in get_video\n    hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subzero\\video.py", line 58, in parse_video\n    skip_hashing=skip_hashing, hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subliminal_patch\\core.py", line 547, in scan_video\n    video.size = os.path.getsize(hash_path)\n  File "C:\\Python27\\lib\\genericpath.py", line 57, in getsize\n    return os.stat(filename).st_size\nWindowsError: [Error 3] The system cannot find the path specified: u\'R:\\\\Sorted\\\\Mr. Robot\\\\Season 3\\\\Mr. Robot - 3x10 - shutdown -r.mkv\''|
06/10/2019 09:58:30|ERROR   |root                            |BAZARR Error trying to get video information for this file: R:\Sorted\Interior Design Masters\Season 1\Interior.Design.Masters.S01E08.HDTV.x264-LiNKLE[eztv].mkv|'Traceback (most recent call last):\n  File "c:\\bazarr\\bazarr\\bazarr\\get_subtitle.py", line 64, in get_video\n    hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subzero\\video.py", line 58, in parse_video\n    skip_hashing=skip_hashing, hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subliminal_patch\\core.py", line 547, in scan_video\n    video.size = os.path.getsize(hash_path)\n  File "C:\\Python27\\lib\\genericpath.py", line 57, in getsize\n    return os.stat(filename).st_size\nWindowsError: [Error 3] The system cannot find the path specified: u\'R:\\\\Sorted\\\\Interior Design Masters\\\\Season 1\\\\Interior Design Masters - 1x08 - Episode 8.mkv\''|
06/10/2019 09:58:30|ERROR   |root                            |BAZARR Error trying to get video information for this file: R:\Movies\I Feel Good (2018)\I.Feel.Good.2018.FRENCH.BDRip.1080p.mkv|'Traceback (most recent call last):\n  File "c:\\bazarr\\bazarr\\bazarr\\get_subtitle.py", line 64, in get_video\n    hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subzero\\video.py", line 58, in parse_video\n    skip_hashing=skip_hashing, hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subliminal_patch\\core.py", line 547, in scan_video\n    video.size = os.path.getsize(hash_path)\n  File "C:\\Python27\\lib\\genericpath.py", line 57, in getsize\n    return os.stat(filename).st_size\nWindowsError: [Error 3] The system cannot find the path specified: u\'R:\\\\Movies\\\\I Feel Good (2018)\\\\I Feel Good (2018).mkv\''|
06/10/2019 09:58:30|INFO    |root                            |BAZARR Finished searching for missing subtitles. Check histories for more information.|
06/10/2019 10:23:34|ERROR   |root                            |BAZARR Error trying to get video information for this file: R:\Sorted\Get Shorty (2017)\Season 3\Get.Shorty.S03E01.1080p.WEB.h264-CONVOY[rarbg].mkv|'Traceback (most recent call last):\n  File "c:\\bazarr\\bazarr\\bazarr\\get_subtitle.py", line 64, in get_video\n    hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subzero\\video.py", line 58, in parse_video\n    skip_hashing=skip_hashing, hash_from=hash_from)\n  File "c:\\bazarr\\bazarr\\bazarr\\../libs/subliminal_patch\\core.py", line 547, in scan_video\n    video.size = os.path.getsize(hash_path)\n  File "C:\\Python27\\lib\\genericpath.py", line 57, in getsize\n    return os.stat(filename).st_size\nWindowsError: [Error 3] The system cannot find the path specified: u\'R:\\\\Sorted\\\\Get Shorty (2017)\\\\Season 3\\\\Get Shorty - 3x01 - What To Do When You Land.mkv\''|
`

**Comment by morpheus65535** [comment]
I still cannot reproduce it. Send me your bazarr.db and I'll to see what's going wrong.

**Comment by mobamoba** [comment]
It's now unable to index external subtitles and went ahead and re-downloaded hundreds of subtitles that already exist. Where should I upload the DB so you can see what's going on? Thanks.

**Comment by morpheus65535** [comment]
In private on Discord.

**Comment by morpheus65535** [comment]
I’ve pushed a fix to dev branch. You can test it?

**Comment by mobamoba** [comment]
It's partially working. I'm not getting that error. However it's also not detecting existing subtitles on all shows and movies. I can see the srt files in the directories and Bazarr is still showing a number of them as "missing subtitles".

**Comment by morpheus65535** [comment]
Can you update dev branch and test again? I've pushed a lot of fix today.

**Comment by mobamoba** [comment]
It's better but it's still not detecting a subtitle that's in the directory and is also trying to download a subtitle for a movie that was deleted months ago.

**Comment by morpheus65535** [comment]
Did you ever think about backing up your database and restart with a brand new one?

**Comment by mobamoba** [comment]
Actually this is. Maybe a few months ago Bazarr stopped auto-updating (I think it was a known issue but I can't remember exactly). Once that was fixed, I wiped everything and rebuilt from scratch so this DB really isn't that old.

**Comment by morpheus65535** [comment]
The symptoms you are mentioning here lead me to a corrupt/out of sync DB. I feel like if we are working to fix issues tied to something else we already fixed...

**Comment by mobamoba** [comment]
Ok. Can i just delete the db then restart bazarr and have it scan the disk and it will build a new db?

**Comment by morpheus65535** [comment]
Yes but you need to select enabled languages on first run.

**Comment by mobamoba** [comment]
So I did that - updated dev branch from git, deleted DB, restarted and picked language then ran through the scan process a few times. It's still failing to detect an existing subtitle on one show and is not detecting a missing subtitle on one movie.

**Comment by morpheus65535** [comment]
This issue is happening only for one show and one movie? Which ones?

**Comment by mobamoba** [comment]
![Untitled](https://user-images.githubusercontent.com/11135869/66389615-c8847180-e996-11e9-8be9-6729fd22b8c6.png)

![Untitled2](https://user-images.githubusercontent.com/11135869/66389630-d4703380-e996-11e9-8bcb-49fdd6793a60.png)

**Comment by morpheus65535** [comment]
Please provide a debug log again. Thanks.

**Comment by mobamoba** [comment]
Here you go:
[bazarr.log](https://github.com/morpheus65535/bazarr/files/3704345/bazarr.log)

**Comment by morpheus65535** [comment]
You have plenty of error in your log. I We are having a lot of issue with 0.8.2.x... I'm working hard to fix everything but I suggest you wait a couple of days and restart from scratch.

**Comment by halali** [comment]
still an issue ?

**Comment by mobamoba** [comment]
Not sure as haven't done a ton of sub downloads recently. If you want close, that's fine - I'll reopen if I see the problem occur again.
