### ISSUE TITLE
Update Movie list from Radarr raised an exception: \NoneType\ object has no attribute \missing_subtitles\

### ISSUE THREAD

**Issue by cdemi** [morpheus65535/bazarr#633]
It looks like every time Bazarr tries to sync with Radarr I get the following exception

**Stack Trace**
```
Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/app/bazarr/bazarr/get_movies.py", line 280, in update_movies
  movies_download_subtitles(altered_movie[2])
 File "/app/bazarr/bazarr/get_subtitle.py", line 697, in movies_download_subtitles
  count_movie = len(ast.literal_eval(movie.missing_subtitles))
AttributeError: \NoneType\ object has no attribute \missing_subtitles\
```

**Software (please complete the following information):**
 - Bazarr: 0.8.2.4
 - Radarr version 0.2.0.1358
 - OS: Linux-4.4.0-154-generic-x86_64-with

**Comment by morpheus65535** [comment]
Same as #634

**Comment by cdemi** [comment]
Thanks for you reply. I have recreated the database from the latest dev branch and I still get this error. Please find attached the database file. If you need any other information, I'm willing to help

[bazarr.zip](https://github.com/morpheus65535/bazarr/files/3729216/bazarr.zip)

**Comment by cdemi** [comment]
Thanks for your quick reply. I have reinitialized the database from latest dev branch but I still get this exception. I have attached the `db` folder

[db.zip](https://github.com/morpheus65535/bazarr/files/3729282/db.zip)

What do you think I'm doing wrong?

**Comment by morpheus65535** [comment]
You really want forced subtitles? I mean, you want both English and English foreign subtitles?

**Comment by cdemi** [comment]
You're right. I will try without forced subtitles

**Comment by cdemi** [comment]
I have changed the default settings and updated the movie list to disable forced subtitles but I still get this same exception

![image](https://user-images.githubusercontent.com/8025435/66897994-85f71080-eff8-11e9-948e-b53f794ccceb.png)

**Comment by cdemi** [comment]
I have changed the default settings and updated the movie list to disable forced subtitles but I still get this same exception
![image](https://user-images.githubusercontent.com/8025435/66898039-9f985800-eff8-11e9-964e-14081e64da73.png)

**Comment by halali** [comment]
Can you try also with disabled hearing impaired... If there will be same issue?

**Comment by cdemi** [comment]
Still the same :(

![image](https://user-images.githubusercontent.com/8025435/66906908-bd6db900-f008-11e9-9d1b-914339b3f1e4.png)
![image](https://user-images.githubusercontent.com/8025435/66906930-c9597b00-f008-11e9-9d77-b11fc73369f1.png)

**Comment by morpheus65535** [comment]
Your database is malformed. Existing subtitles task haven't completed yet. Please for the execution of the `Update all Movie Subtitles from disk` task then try again.

**Comment by cdemi** [comment]
I've updated all movie subtitles from disk (waited for the following progress bar to complete)

![image](https://user-images.githubusercontent.com/8025435/66914923-1b55cd00-f018-11e9-90b7-2585117e12b0.png)
![image](https://user-images.githubusercontent.com/8025435/66915200-bb135b00-f018-11e9-8818-5496e37f6933.png)

I tried to Update the movie list but still the same:
![image](https://user-images.githubusercontent.com/8025435/66915315-ff066000-f018-11e9-8c8c-195c0af72238.png)

I have attached the db after a full "Update all Movie Subtitles from disk"
[db.zip](https://github.com/morpheus65535/bazarr/files/3734029/db.zip)

**Comment by morpheus65535** [comment]
I'm working to fix it. Thanks for those informations.

**Comment by cdemi** [comment]
Thank you very much. Appreciate it
________________________________

**Comment by mouzzampk2014** [comment]
Morph same issue happening here and I'm getting these a lot on logs. Just to update you :)

**Comment by morpheus65535** [comment]
@mouzzampk2014 Thanks. I,m reworking the hole DB stuff and get back to normal SQlite without Peewee ORM that have been causing all that trouble since v0.8.2.

**Comment by mouzzampk2014** [comment]
> @mouzzampk2014 Thanks. I,m reworking the hole DB stuff and get back to normal SQlite without Peewee ORM that have been causing all that trouble since v0.8.2. Should be out in a week in dev.

Coolio and thank you for looking into this

**Comment by morpheus65535** [comment]
Should be fixed in 0.8.3 currently in dev branch. Please reopen if it's not the case.

**Comment by cdemi** [comment]
Do you know if we need to re-init the database? After upgrade I still get the error, but I haven't inited the database

**Comment by mouzzampk2014** [comment]
Hi Morph same here :)

**Comment by morpheus65535** [comment]
Force a full scan from disk in tasks. Provide a new stack trace please.

**Comment by cdemi** [comment]
> Force a full scan from disk in tasks
Update all Movie Subtitles from disk finished successfully, no exceptions.

>Update Movie list from Radarr
Ran this after full disk scan and I got an exception, but it looks like it's a different exception than before:
```
Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/app/bazarr/bazarr/get_movies.py", line 262, in update_movies
  movies_download_subtitles(altered_movie[2])
 File "/app/bazarr/bazarr/get_subtitle.py", line 665, in movies_download_subtitles
  if ast.literal_eval(movie[\missing_subtitles\]):
TypeError: \NoneType\ object has no attribute \__getitem__\
```

**Comment by morpheus65535** [comment]
Can you provide a full debug log please?

**Comment by cdemi** [comment]
Is this good?

[bazarr.log](https://github.com/morpheus65535/bazarr/files/3783081/bazarr.log)

**Comment by morpheus65535** [comment]
Can you update and test again please? Should be fixed.

**Comment by cdemi** [comment]
Thanks! I need to wait for [the docker image to be built](https://hub.docker.com/r/linuxserver/bazarr/tags?page=1&ordering=last_updated). I will update you later

**Comment by morpheus65535** [comment]
Should be ready in 20 minutes.

**Comment by morpheus65535** [comment]
Done

**Comment by cdemi** [comment]
for some weird reason even though I am running on the container for commit dd41a30ab1b472a1ee8924ae2150c4a9bac72e98 I am still seeing version `0.8.3` on bazaar and I'm still getting the exception:

```
Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/app/bazarr/bazarr/get_movies.py", line 262, in update_movies
  movies_download_subtitles(altered_movie[2])
 File "/app/bazarr/bazarr/get_subtitle.py", line 665, in movies_download_subtitles
  if ast.literal_eval(movie[\missing_subtitles\]):
TypeError: \NoneType\ object has no attribute \__getitem__\
```

**Comment by morpheus65535** [comment]
I've added more debug logging to better understand what is the issue. Please update with new container in 45 minutes and provide a new debug log please. Thanks!

**Comment by cdemi** [comment]
I have attached a new debug log file

[bazarr.log](https://github.com/morpheus65535/bazarr/files/3785472/bazarr.log)

**Comment by morpheus65535** [comment]
You can send me your bazarr.db?

**Comment by cdemi** [comment]
Attached

[bazarr.zip](https://github.com/morpheus65535/bazarr/files/3785517/bazarr.zip)

**Comment by morpheus65535** [comment]
You have Ghostbuster(1984) indexed in Radarr as the 2016 eponymous movie. This cause a UNIQUE constraint failure when inserting the second one in Bazarr DB. I will add a fail safe for that but you should correct this issue in Radarr.

**Comment by cdemi** [comment]
I can confirm this is fixed. Thanks a lot dude

**Comment by mouzzampk2014** [comment]
I'm still getting these raised an exception, might be same as above?

**Comment by morpheus65535** [comment]
Send me debug and db.
