### ISSUE TITLE
BAZARR unable to index external subtitles.

### ISSUE THREAD

**Issue by martijnk-cmd** [morpheus65535/bazarr#709]
Latest Bazarr dev Python 3.6 on FreeBSD 12.1

Bazarr throws an error when doing an update all subtitles from disk. It generates one error for each movie/episode file.

Here's the debug log:

```
Traceback (most recent call last):
 File "/usr/local/bazarr/bazarr/list_subtitles.py", line 143, in store_subtitles_movie
  subtitles = search_external_subtitles(reversed_path, languages=get_language_set())
 File "/usr/local/bazarr/bazarr/../libs/subliminal_patch/core.py", line 669, in search_external_subtitles
  only_one=only_one, match_strictness=match_strictness))
 File "/usr/local/bazarr/bazarr/../libs/subliminal_patch/core.py", line 584, in _search_external_subtitles
  if not entry.is_file(follow_symlinks=False):
 File "/usr/local/bazarr/bazarr/../libs/scandir.py", line 500, in is_file
  st = self.stat(follow_symlinks=follow_symlinks)
 File "/usr/local/bazarr/bazarr/../libs/scandir.py", line 480, in stat
  self._lstat = lstat(self.path)
 File "/usr/local/bazarr/bazarr/../libs/scandir.py", line 465, in path
  self._path = join(self._scandir_path, self.name)
 File "/usr/local/lib/python3.6/posixpath.py", line 94, in join
  genericpath._check_arg_types(\join\, a, *p)
 File "/usr/local/lib/python3.6/genericpath.py", line 151, in _check_arg_types
  raise TypeError("Can\t mix strings and bytes in path components") from None
TypeError: Can\t mix strings and bytes in path components
```

**Comment by morpheus65535** [comment]
What file system type is hosting you media files?

**Comment by martijnk-cmd** [comment]
ZFS

________________________________

**Comment by morpheus65535** [comment]
Could you try to edit `bazarr/bazarr/libs/scandir.py` at line 465? Please try to replace with both variant? I'm not sure which one is the string and binary:

`self._path = join(self._scandir_path.decode(encoding="utf-8"), self.name)`
or
`self._path = join(self._scandir_path, self.name.decode(encoding="utf-8"))`

You have to restart Bazarr after editing a file. Take a backup of `scandir.py` first.

**Comment by martijnk-cmd** [comment]
I've tested both and in both occassions I get:

`Traceback (most recent call last):
 File "/usr/local/bazarr/bazarr/list_subtitles.py", line 143, in store_subtitles_movie
  subtitles = search_external_subtitles(reversed_path, languages=get_language_set())
 File "/usr/local/bazarr/bazarr/../libs/subliminal_patch/core.py", line 669, in search_external_subtitles
  only_one=only_one, match_strictness=match_strictness))
 File "/usr/local/bazarr/bazarr/../libs/subliminal_patch/core.py", line 584, in _search_external_subtitles
  if not entry.is_file(follow_symlinks=False):
 File "/usr/local/bazarr/bazarr/../libs/scandir.py", line 500, in is_file
  st = self.stat(follow_symlinks=follow_symlinks)
 File "/usr/local/bazarr/bazarr/../libs/scandir.py", line 480, in stat
  self._lstat = lstat(self.path)
 File "/usr/local/bazarr/bazarr/../libs/scandir.py", line 465, in path
  self._path = join(self._scandir_path, self.name.decode(encoding="utf-8"))
AttributeError: \str\ object has no attribute \decode\`

Thanks for taking the effort to fix this btw!

**Comment by morpheus65535** [comment]
Both having this exact same error? `AttributeError: \str\ object has no attribute \decode\`

It doesn’t make sense as it was complaining about one being byte and one string in your original error...

**Comment by martijnk-cmd** [comment]
Yes here are both errors

`Traceback (most recent call last):
 File "/usr/local/bazarr/bazarr/list_subtitles.py", line 143, in store_subtitles_movie
  subtitles = search_external_subtitles(reversed_path, languages=get_language_set())
 File "/usr/local/bazarr/bazarr/../libs/subliminal_patch/core.py", line 669, in search_external_subtitles
  only_one=only_one, match_strictness=match_strictness))
 File "/usr/local/bazarr/bazarr/../libs/subliminal_patch/core.py", line 584, in _search_external_subtitles
  if not entry.is_file(follow_symlinks=False):
 File "/usr/local/bazarr/bazarr/../libs/scandir.py", line 500, in is_file
  st = self.stat(follow_symlinks=follow_symlinks)
 File "/usr/local/bazarr/bazarr/../libs/scandir.py", line 480, in stat
  self._lstat = lstat(self.path)
 File "/usr/local/bazarr/bazarr/../libs/scandir.py", line 465, in path
  self._path = join(self._scandir_path.decode(encoding="utf-8"), self.name)
AttributeError: \str\ object has no attribute \decode\

Traceback (most recent call last):
 File "/usr/local/bazarr/bazarr/list_subtitles.py", line 143, in store_subtitles_movie
  subtitles = search_external_subtitles(reversed_path, languages=get_language_set())
 File "/usr/local/bazarr/bazarr/../libs/subliminal_patch/core.py", line 669, in search_external_subtitles
  only_one=only_one, match_strictness=match_strictness))
 File "/usr/local/bazarr/bazarr/../libs/subliminal_patch/core.py", line 584, in _search_external_subtitles
  if not entry.is_file(follow_symlinks=False):
 File "/usr/local/bazarr/bazarr/../libs/scandir.py", line 500, in is_file
  st = self.stat(follow_symlinks=follow_symlinks)
 File "/usr/local/bazarr/bazarr/../libs/scandir.py", line 480, in stat
  self._lstat = lstat(self.path)
 File "/usr/local/bazarr/bazarr/../libs/scandir.py", line 465, in path
  self._path = join(self._scandir_path, self.name.decode(encoding="utf-8"))
AttributeError: \str\ object has no attribute \decode\`

**Comment by morpheus65535** [comment]
Are you sure you've tested with the same episode/movie that was causing the original issue?

**Comment by martijnk-cmd** [comment]
Yes but it happens with any movie/episode.

________________________________

**Comment by morpheus65535** [comment]
I've pushed a fix to dev branch. Could you test it please?

**Comment by martijnk-cmd** [comment]
Hi I did a git pull the file was updated indeed but I still get the same error:

Traceback (most recent call last):
 File "/usr/local/bazarr/bazarr/list_subtitles.py", line 68, in store_subtitles
  only_one=settings.general.getboolean(\single_language\))
 File "/usr/local/bazarr/bazarr/../libs/subliminal_patch/core.py", line 669, in search_external_subtitles
  only_one=only_one, match_strictness=match_strictness))
 File "/usr/local/bazarr/bazarr/../libs/subliminal_patch/core.py", line 584, in _search_external_subtitles
  if not entry.is_file(follow_symlinks=False):
 File "/usr/local/bazarr/bazarr/../libs/scandir.py", line 509, in is_file
  st = self.stat(follow_symlinks=follow_symlinks)
 File "/usr/local/bazarr/bazarr/../libs/scandir.py", line 489, in stat
  self._lstat = lstat(self.path)
 File "/usr/local/bazarr/bazarr/../libs/scandir.py", line 474, in path
  self._path = join(self._scandir_path, self.name)
 File "/usr/local/lib/python3.6/posixpath.py", line 94, in join
  genericpath._check_arg_types(\join\, a, *p)
 File "/usr/local/lib/python3.6/genericpath.py", line 151, in _check_arg_types
  raise TypeError("Can\t mix strings and bytes in path components") from None
TypeError: Can\t mix strings and bytes in path components

**Comment by morpheus65535** [comment]
Something is weird with your error, it complain about one argument of join being a bytes instead of a string. I make a patch that check both arguments and if they are bytes they get converted to string. It should work. I'm starting to worry about something wrong with Python 3.6... Could it be possible to test with something newer?

**Comment by martijnk-cmd** [comment]
I’ve tested with 3.7 but it gives the same error, couldn’t test 3.8 on FreeBSD since the sqlite3 package for that version is not available.

**Comment by morpheus65535** [comment]
I've made another attempt to fix your issue. As I'm going blindly, it may probably take a couple of attempts... Please test it and give me a new trace of the error. Thanks!

**Comment by martijnk-cmd** [comment]
Wow that actually did it! No more errors now, awesome, thanks for the fix!

**Comment by martijnk-cmd** [comment]
I wonder though if it even works right now, I see it downloading subs for a movie, multiple times. But when you click the movie it still says all subs are missing although they are downloaded. When I re-scan the disk same thing, subs missing.

**Comment by morpheus65535** [comment]
Maybe I can get something from a debug log... without it I'm totally blind.

**Comment by mvanbaak** [comment]
Can you please re-open this one?
The problem is with the detection wether scandir returned results or wether it should fallback to scandir_generic.
I'm trying to figure out why.

**Comment by mvanbaak** [comment]
The problem is with the scandir package. The version included does not give correct results for 90% of the directories I tested it on.
The good news is that scandir is available in python as os.scandir, and that version works 100% of the time.
Will create a PR to fix this.

**Comment by morpheus65535** [comment]
Should have been fixed by @mvanbaak in dev branch. Thanks to him!

**Comment by martijnk-cmd** [comment]
Awesome, I was already back to Subliminal cmd :) Will test this thanks!

**Comment by mkools** [comment]
Finally got a chance to test this while being in lock down, it works great now, no more errors. Thanks all for your efforts!!
