### ISSUE TITLE
Encoding problem with tv series path

### ISSUE THREAD

**Issue by ngosang** [morpheus65535/bazarr#718]
Thank you for porting this program to python3. I'm testing the latest version in python3 to see if everything is right.

**Describe the bug**
Encoding problem with tv series path. Check the path for the tv series Capítulo 0
I tested in python2 and python3 and the bug is in both versions.

![image](https://user-images.githubusercontent.com/10577978/71548171-b10fc000-29aa-11ea-8f70-9de31060805b.png)
![image](https://user-images.githubusercontent.com/10577978/71548181-ca187100-29aa-11ea-8e86-593be5c59b08.png)

**Software:**
 - Bazarr Ver. 0.8.4 
 - Python 3.6.8
 - Linux

**Comment by morpheus65535** [comment]
Thank you for taking the time to test this new release. I have a lot of path with accented characters (namely `é`, `è`, `à` and `ù`) and haven't issue with those path. Your issue is probably due to an incorrectly set locale. Make sure you are using an utf8 locale. Could be helpful: https://stackoverflow.com/questions/32794071/filename-encoding-issue-in-python3-linux

**Comment by ngosang** [comment]
@morpheus65535 the path problem is fixed. It was something related to the filesystem. I moved from NTFS to EXT4 recently and something went wrong. I deleted the series from Sonarr and the folder and added it again. Now the path is fine in Sonarr and Bazarr.

I think I found another issue.
1. Add "Capítulo 0" tv series in Sonarr
2. This series has poster but doesn't have overview.
![image](https://user-images.githubusercontent.com/10577978/71563526-2e156500-2a91-11ea-98db-f5499406b72a.png)
3. Sync with Bazarr
4. You can't see the poster
![image](https://user-images.githubusercontent.com/10577978/71563538-52714180-2a91-11ea-9556-58fc0d5af62c.png)
5. The Bazarr database looks like this.
![image](https://user-images.githubusercontent.com/10577978/71563542-69b02f00-2a91-11ea-82fc-ef9c5a45e816.png)

**Comment by morpheus65535** [comment]
This issue have been fixed in dev branch last night. If Sonarr have the information, Bazarr should update it accordingly.

**Comment by ngosang** [comment]
@morpheus65535 I tested the develoment branch and the issue is not fixed. I think the problem is not the sync with sonarr. Check what happens when the tv series doesn't have overview.

**Comment by morpheus65535** [comment]
Should be fixed now in dev branch. Can you confirm?

**Comment by ngosang** [comment]
Tested. It's working fine. Thank you!
