### ISSUE TITLE
No History after update

### ISSUE THREAD

**Issue by Bouncy2020** [morpheus65535/bazarr#790]
after a update last month i get no history and the Post-processing command don't work
also the  notification doesn;t work..  The test works good, but the serie spam not.

**Comment by morpheus65535** [comment]
There's been some significant changes to post-processing in dev branch that should hep you. I should merge this to master tonight.

**Comment by Bouncy2020** [comment]
and it is fixed with the update, thx

**Comment by morpheus65535** [comment]
Good news!

**Comment by kanine** [comment]
I've just updated from development branch and still seeing the following error in the the command window.

Python: 3.8.1

```
Traceback (most recent call last):
  File "d:\apps\bazarr\bazarr\../libs\bottle.py", line 866, in _handle
    return route.call(**args)
  File "d:\apps\bazarr\bazarr\../libs\bottle.py", line 1744, in wrapper
    rv = callback(*a, **ka)
  File "d:\apps\bazarr\bazarr\main.py", line 132, in wrapper
    return func(*a, **ka)
  File "d:\apps\bazarr\bazarr\main.py", line 963, in historyseries
    now = datetime.now()
AttributeError: module 'datetime' has no attribute 'now'
```

**Comment by morpheus65535** [comment]
@kanine fixed in dev branch. Thanks for reporting.
