### ISSUE TITLE
Slack notifications via webhooks not working

### ISSUE THREAD

**Issue by vkojchevski** [morpheus65535/bazarr#883]
**Describe the bug**
Notifications via Slack fail because of invalid (second) token

**To Reproduce**
1. Enable Slack notifications
2. Enter the full webhook copied directly from Slack website
3. Test connection
4. Messages are not transmitted

**Expected behavior**
Notification messages should be transmitted to Slack

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: 0.8.4.2 
 - Radarr version 0.2.0.1480
 - Sonarr version 2.0.0.5344
 - OS: Docker on Unraid 6.8.3

**Additional context**
I think I narrowed the issue down. I tested with some old webhooks I had active and the notifications worked. What is different from the newly generated webhooks is that the second token is now 11 characters long instead of the previous 9, which Apprise considers to be an invalid format.

After some searching I found this commit fixing the issue: https://github.com/caronc/apprise/commit/3895ad9b58eeffa876079d984acda7a61c3b3633. Considering Bazarr runs Apprise 0.8.2 and there are few newer releases from caronc, is it safe to assume that the version will be updated eventually (and this Slack notification issue resolved)?

**Comment by morpheus65535** [comment]
Should be fixed in dev branch with latest apprise.

**Comment by vkojchevski** [comment]
I am not really savvy so please excuse me if I am missing something obvious.

I've switched to the development tag on Linuxserver's Bazarr docker, running version 0.8.4.3 of Bazaar. The issue is still present. Invalid second token.

Looking at https://github.com/morpheus65535/bazarr/blob/development/libs/apprise/plugins/NotifySlack.py, I've noticed the problematic code is still there, https://github.com/morpheus65535/bazarr/blob/d1a94638e170259d80e12722db3de887c2eb8fb6/libs/apprise/plugins/NotifySlack.py#L179 https://github.com/morpheus65535/bazarr/blob/d1a94638e170259d80e12722db3de887c2eb8fb6/libs/apprise/plugins/NotifySlack.py#L188 https://github.com/morpheus65535/bazarr/blob/d1a94638e170259d80e12722db3de887c2eb8fb6/libs/apprise/plugins/NotifySlack.py#L197

Still limiting the number of characters per token to {9},{9},{24} respectively, which is completely removed by the PR I linked previously, merged 5 days ago on the apprise repo if I am not mistaken.

**Comment by morpheus65535** [comment]
Sorry I was thinking that this fix was in the latest release (0.8.4) of Apprise. We'll have to wait for a new release.

@caronc are you planning to release soon?

**Comment by vkojchevski** [comment]
Ah I wasn't aware of that fact either, my bad. That is fair, it's a minor issue anyway.

As far as I am concerned, this issue is resolved considering it is only a matter of time and administrative work to get the fix implemented. Being inexperienced GitHub user myself, I am not sure if I should close the issue now or wait until a later date when the fix is merged.

**Comment by morpheus65535** [comment]
Let's keep it open as a reminder to me to merge next release of Apprise.

**Comment by caronc** [comment]
@morpheus65535 I really want to get in [this ticket](https://github.com/caronc/apprise/issues/213) which has a pull request that works great. The problem is it is missing some unit tests to complete the full coverage. I will do an Apprise release shortly thereafter if I can, but it may still linger another week or so... sorry. 

The changes you identified are all you need to update to fix the Slack problem.  Feel free to patch your version if you need to.  I promise to keep you posted when i do a release though! :slightly_smiling_face:

**Comment by morpheus65535** [comment]
Should be fixed now in dev branch.
